-- Real Indonesia open-data seed pack.
-- Sources are public/free sources only. Rows are references, not fake sellers.

DELETE FROM content_items
WHERE metadata->>'seed_pack' = 'real_indonesia_open_data_20260723';

DELETE FROM umkm_stores
WHERE metadata->>'seed_pack' = 'real_indonesia_open_data_20260723';

INSERT INTO users_read_model (
  user_id,
  email,
  username,
  full_name,
  avatar_url,
  email_verified,
  phone_verified,
  identity_verified,
  transaction_eligible,
  status,
  metadata,
  identity_version,
  identity_updated_at,
  synced_at
)
VALUES (
  '00000000-0000-0000-0000-000000000801',
  'open-data@lajukan.seed',
  'lajukan_open_data',
  'Lajukan Open Data',
  '',
  TRUE,
  FALSE,
  FALSE,
  FALSE,
  'active',
  '{"seed_pack":"real_indonesia_open_data_20260723","account_type":"system_seed_curator","contact_policy":"no_private_contact_seeded","description":"Curated public Indonesia datasets and free media references for local development."}'::jsonb,
  1,
  NOW(),
  NOW()
)
ON CONFLICT (user_id) DO UPDATE
SET email = EXCLUDED.email,
    username = EXCLUDED.username,
    full_name = EXCLUDED.full_name,
    avatar_url = EXCLUDED.avatar_url,
    email_verified = EXCLUDED.email_verified,
    phone_verified = EXCLUDED.phone_verified,
    identity_verified = EXCLUDED.identity_verified,
    transaction_eligible = EXCLUDED.transaction_eligible,
    status = EXCLUDED.status,
    metadata = COALESCE(users_read_model.metadata, '{}'::jsonb) || EXCLUDED.metadata,
    identity_version = EXCLUDED.identity_version,
    identity_updated_at = EXCLUDED.identity_updated_at,
    synced_at = NOW();

UPDATE content_items
SET content_status = 'archived',
    metadata = COALESCE(metadata, '{}'::jsonb)
      || jsonb_build_object(
        'archived_by_seed_pack', 'real_indonesia_open_data_20260723',
        'archived_reason', 'Fictional demo data hidden so real open-data references become the primary seed surface.'
      ),
    updated_at = NOW()
WHERE metadata->>'seed_pack' = 'indonesia_demo_20260709'
  AND content_status = 'active';

UPDATE umkm_stores
SET is_active = FALSE,
    online_order_enabled = FALSE,
    offline_order_enabled = FALSE,
    metadata = COALESCE(metadata, '{}'::jsonb)
      || jsonb_build_object(
        'archived_by_seed_pack', 'real_indonesia_open_data_20260723',
        'archived_reason', 'Fictional demo store hidden by real open-data seed pack.'
      ),
    updated_at = NOW()
WHERE metadata->>'seed_pack' = 'indonesia_demo_20260709'
  AND is_active = TRUE;

UPDATE umkm_products
SET is_available = FALSE,
    metadata = COALESCE(metadata, '{}'::jsonb)
      || jsonb_build_object(
        'archived_by_seed_pack', 'real_indonesia_open_data_20260723',
        'archived_reason', 'Fictional demo product hidden by real open-data seed pack.'
      ),
    updated_at = NOW()
WHERE metadata->>'seed_pack' = 'indonesia_demo_20260709'
  AND is_available = TRUE;

WITH real_items (
  content_type,
  slug,
  title,
  summary,
  body,
  price_unit,
  tags,
  cover_image,
  category,
  city,
  location_text,
  lat,
  lng,
  create_category,
  marketplace_category_slug,
  source_title,
  source_url,
  source_license,
  media_provider,
  media_title,
  media_source_url,
  media_author,
  media_license_url,
  media_license_name
) AS (
  VALUES
    (
      'guide',
      'data-bkpm-jumlah-umkm-nib-2025',
      'Data BKPM: jumlah UMKM yang memiliki NIB tahun 2025',
      'Dataset publik jumlah pelaku UMKM yang memiliki Nomor Induk Berusaha dari OSS/BKPM.',
      'Referensi legalitas usaha untuk memahami sebaran UMKM yang sudah memiliki NIB. Data ini bukan listing penjual; gunakan sebagai konteks pencarian supplier, legalitas, dan pemetaan peluang daerah.',
      'dataset',
      ARRAY['data real','umkm','nib','oss','legalitas usaha','bkpm'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Jalan-jalan_ke_Pasar_Beringharjo-12.jpg?width=1200',
      'service',
      'Indonesia',
      'Indonesia',
      NULL,
      NULL,
      'service',
      'services',
      'Jumlah UMKM yang Memiliki Izin Usaha NIB Tahun 2025',
      'https://data.bkpm.go.id/dataset-detail/jumlah-umkm-yang-memiliki-izin-usaha-nib-tahun-2025',
      'Publik',
      'Wikimedia Commons',
      'Jalan-jalan ke Pasar Beringharjo-12.jpg',
      'https://commons.wikimedia.org/wiki/File:Jalan-jalan_ke_Pasar_Beringharjo-12.jpg',
      'Indonesiagood',
      'https://creativecommons.org/licenses/by/3.0/',
      'CC BY 3.0'
    ),
    (
      'guide',
      'data-bps-profil-industri-mikro-kecil-2024',
      'BPS: Profil Industri Mikro dan Kecil 2024',
      'Publikasi tahunan BPS tentang karakteristik Industri Mikro dan Kecil Indonesia.',
      'BPS mencatat IMK sebagai sektor penting untuk lapangan kerja lokal dan memetakan tantangan seperti akses modal, kualitas SDM, manajemen, dan legalitas. Seed ini memberi konteks nyata untuk kebutuhan bahan usaha, jasa pendampingan, dan legalitas.',
      'publikasi',
      ARRAY['data real','bps','imk','industri mikro','industri kecil','umkm'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Batik_Khas_Pekalongan.jpg?width=1200',
      'service',
      'Indonesia',
      'Indonesia',
      NULL,
      NULL,
      'service',
      'services',
      'Profil Industri Mikro dan Kecil 2024',
      'https://www.bps.go.id/assets/publication/2025/09/16/a83f105e49377d0a7434e62a/profil-industri-mikro-dan-kecil-2024.html',
      'BPS public publication',
      'Wikimedia Commons',
      'Batik Khas Pekalongan.jpg',
      'https://commons.wikimedia.org/wiki/File:Batik_Khas_Pekalongan.jpg',
      'Sekar Jarwo Soekarno',
      'https://creativecommons.org/licenses/by/4.0/',
      'CC BY 4.0'
    ),
    (
      'material',
      'kopi-arabika-gayo-indikasi-geografis-dgip',
      'Kopi Arabika Gayo - Indikasi Geografis terdaftar',
      'Referensi komoditas kopi Indonesia dari daftar Indikasi Geografis DJKI.',
      'Kopi Arabika Gayo tercatat dalam listing Indikasi Geografis DJKI dengan nomor IG.00.2009.000003 dan lokasi Aceh. Seed ini tidak mewakili satu supplier; ini referensi asal produk untuk pencarian bahan usaha kopi.',
      'referensi',
      ARRAY['kopi gayo','indikasi geografis','dgip','aceh','bahan usaha','kopi indonesia'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Coffee_beans_from_Tasikmalaya_in_a_glass_container_20170518.jpg?width=1200',
      'material',
      'Aceh',
      'Aceh, Indonesia',
      4.695135,
      96.749397,
      'supplies',
      'materials-suppliers',
      'Listing Indikasi Geografis Terdaftar - Kopi',
      'https://www.dgip.go.id/menu-utama/indikasi-geografis/listing?category=ip_clinic&keyword=kopi',
      'Public government registry',
      'Wikimedia Commons',
      'Coffee beans from Tasikmalaya in a glass container 20170518.jpg',
      'https://commons.wikimedia.org/wiki/File:Coffee_beans_from_Tasikmalaya_in_a_glass_container_20170518.jpg',
      'Abdulrohmatt',
      'https://creativecommons.org/licenses/by-sa/4.0/',
      'CC BY-SA 4.0'
    ),
    (
      'material',
      'kopi-arabika-kintamani-bali-indikasi-geografis-dgip',
      'Kopi Arabika Kintamani Bali - Indikasi Geografis terdaftar',
      'Referensi komoditas kopi Bali dari daftar Indikasi Geografis DJKI.',
      'Kopi Arabika Kintamani Bali tercatat dalam listing Indikasi Geografis DJKI dengan nomor IG.00.2007.000001 dan lokasi Bali. Gunakan sebagai referensi asal bahan, bukan klaim stok atau harga supplier.',
      'referensi',
      ARRAY['kopi kintamani','indikasi geografis','dgip','bali','bahan usaha','kopi indonesia'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Coffee_beans_from_Tasikmalaya_in_a_glass_container_20170518.jpg?width=1200',
      'material',
      'Bali',
      'Bali, Indonesia',
      -8.409518,
      115.188919,
      'supplies',
      'materials-suppliers',
      'Listing Indikasi Geografis Terdaftar - Kopi',
      'https://www.dgip.go.id/menu-utama/indikasi-geografis/listing?category=ip_clinic&keyword=kopi',
      'Public government registry',
      'Wikimedia Commons',
      'Coffee beans from Tasikmalaya in a glass container 20170518.jpg',
      'https://commons.wikimedia.org/wiki/File:Coffee_beans_from_Tasikmalaya_in_a_glass_container_20170518.jpg',
      'Abdulrohmatt',
      'https://creativecommons.org/licenses/by-sa/4.0/',
      'CC BY-SA 4.0'
    ),
    (
      'property',
      'pasar-beringharjo-yogyakarta-open-data',
      'Pasar Beringharjo Yogyakarta - referensi pasar real',
      'Pasar tradisional dan sentra belanja di Yogyakarta dengan data cagar budaya dan media bebas.',
      'Pasar Beringharjo adalah pasar nyata di Yogyakarta. Seed ini memakai sumber publik dan tidak menampilkan nomor kontak privat. Cocok sebagai referensi lokasi untuk batik, oleh-oleh, makanan, dan perdagangan pasar tradisional.',
      'referensi',
      ARRAY['pasar beringharjo','yogyakarta','batik','oleh-oleh','pasar tradisional','tempat usaha'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Jalan-jalan_ke_Pasar_Beringharjo-12.jpg?width=1200',
      'property',
      'Yogyakarta',
      'Jl. Marga Mulya No.16, Yogyakarta',
      -7.798925,
      110.365616,
      'property',
      'business-places',
      'Cagar Budaya - Pasar Beringharjo',
      'https://budaya.data.kemdikbud.go.id/cagarbudaya/objek/KB001567',
      'Public cultural heritage data',
      'Wikimedia Commons',
      'Jalan-jalan ke Pasar Beringharjo-12.jpg',
      'https://commons.wikimedia.org/wiki/File:Jalan-jalan_ke_Pasar_Beringharjo-12.jpg',
      'Indonesiagood',
      'https://creativecommons.org/licenses/by/3.0/',
      'CC BY 3.0'
    ),
    (
      'property',
      'pasar-tanah-abang-jakarta-open-data',
      'Pasar Tanah Abang Jakarta - referensi pasar tekstil real',
      'Kawasan pasar tekstil besar di Jakarta Pusat dari sumber Wikimedia/Wikidata.',
      'Tanah Abang adalah kawasan nyata di Jakarta Pusat dan dikenal sebagai pusat perdagangan tekstil. Seed ini adalah referensi lokasi, bukan toko individual atau penawaran sewa.',
      'referensi',
      ARRAY['tanah abang','jakarta','tekstil','grosir','pasar','tempat usaha'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Flood_Canal_Bisecting_Pasar_Tanah_Abang.jpg?width=1200',
      'property',
      'Jakarta Pusat',
      'Tanah Abang, Jakarta Pusat',
      -6.2028,
      106.8196,
      'property',
      'business-places',
      'Wikimedia Commons Category: Tanah Abang',
      'https://commons.wikimedia.org/wiki/Category:Tanah_Abang',
      'Free Wikimedia text/media subject page',
      'Wikimedia Commons',
      'Flood Canal Bisecting Pasar Tanah Abang.jpg',
      'https://commons.wikimedia.org/wiki/File:Flood_Canal_Bisecting_Pasar_Tanah_Abang.jpg',
      'christian r',
      'https://creativecommons.org/licenses/by-sa/2.0/',
      'CC BY-SA 2.0'
    ),
    (
      'property',
      'pasar-klewer-surakarta-open-data',
      'Pasar Klewer Surakarta - referensi sentra tekstil real',
      'Pasar tekstil dan batik di Surakarta dengan referensi OSM/Wikidata.',
      'Pasar Klewer adalah marketplace nyata di Solo/Surakarta. Data koordinat dan kategori lokasi disimpan sebagai referensi publik; tidak ada nomor kontak atau klaim ketersediaan kios.',
      'referensi',
      ARRAY['pasar klewer','solo','surakarta','batik','tekstil','tempat usaha'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Pasar_Klewer.jpg?width=1200',
      'property',
      'Surakarta',
      'Pasar Klewer, Surakarta, Jawa Tengah',
      -7.57547,
      110.82653,
      'property',
      'business-places',
      'Indonesia Travel - Pasar Klewer',
      'https://www.indonesia.travel/id/id/destination/java/central-java/klewer-market',
      'Public tourism reference',
      'Wikimedia Commons',
      'Pasar Klewer.jpg',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer.jpg',
      'CoolFrame Photography / WikiSanktGerard',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer.jpg',
      'Public domain'
    ),
    (
      'property',
      'kampung-batik-laweyan-surakarta-open-data',
      'Kampung Batik Laweyan Surakarta - referensi sentra batik real',
      'Kawasan Laweyan di Surakarta sebagai referensi ekosistem batik dan usaha kreatif.',
      'Laweyan adalah kecamatan nyata di Surakarta dan dikenal sebagai kawasan batik. Seed ini membantu discovery sentra batik tanpa mengklaim stok, harga, atau kontak toko tertentu.',
      'referensi',
      ARRAY['laweyan','kampung batik','surakarta','batik','ekonomi kreatif','tempat usaha'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Becak_Kampung_Batik_Laweyan.jpg?width=1200',
      'property',
      'Surakarta',
      'Laweyan, Surakarta, Jawa Tengah',
      -7.56083,
      110.79306,
      'property',
      'business-places',
      'Kampoeng Batik Laweyan',
      'https://kampoengbatiklaweyan.org/',
      'Public website reference',
      'Wikimedia Commons',
      'Becak Kampung Batik Laweyan.jpg',
      'https://commons.wikimedia.org/wiki/File:Becak_Kampung_Batik_Laweyan.jpg',
      'Herusutimbul',
      'https://creativecommons.org/licenses/by-sa/4.0/',
      'CC BY-SA 4.0'
    ),
    (
      'property',
      'pasar-terapung-lok-baintan-banjar-open-data',
      'Pasar Terapung Lok Baintan Banjar - referensi pasar sungai real',
      'Pasar terapung nyata di Sungai Pinang, Kabupaten Banjar, Kalimantan Selatan.',
      'Pasar Terapung Lok Baintan adalah pasar budaya dan perdagangan sungai yang nyata. Seed ini menyimpan koordinat dan media bebas sebagai referensi lokasi, bukan listing dagang individual.',
      'referensi',
      ARRAY['lok baintan','pasar terapung','kalimantan selatan','banjar','pasar tradisional','tempat usaha'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Lokbaintan.jpg?width=1200',
      'property',
      'Banjar',
      'Sungai Pinang, Kabupaten Banjar, Kalimantan Selatan',
      -3.296355,
      114.691953,
      'property',
      'business-places',
      'Wikimedia Commons Category: Lok Baintan Floating Market',
      'https://commons.wikimedia.org/wiki/Category:Lok_Baintan_Floating_Market',
      'Free Wikimedia text/media subject page',
      'Wikimedia Commons',
      'Lokbaintan.jpg',
      'https://commons.wikimedia.org/wiki/File:Lokbaintan.jpg',
      'Rifki Muslim',
      'https://creativecommons.org/licenses/by-sa/4.0/',
      'CC BY-SA 4.0'
    ),
    (
      'material',
      'batik-pekalongan-referensi-media-bebas',
      'Batik Pekalongan - referensi produk budaya Indonesia',
      'Referensi visual batik Pekalongan dari media bebas Wikimedia Commons.',
      'Batik Pekalongan adalah produk budaya nyata Indonesia. Seed ini memberi contoh visual dan konteks pencarian untuk pelaku usaha batik tanpa membuat klaim toko, harga, atau stok.',
      'referensi',
      ARRAY['batik pekalongan','batik','produk budaya','tekstil','bahan usaha','indonesia'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Batik_Khas_Pekalongan.jpg?width=1200',
      'material',
      'Pekalongan',
      'Pekalongan, Jawa Tengah',
      -6.8898,
      109.6753,
      'supplies',
      'materials-suppliers',
      'Wikimedia Commons File: Batik Khas Pekalongan.jpg',
      'https://commons.wikimedia.org/wiki/File:Batik_Khas_Pekalongan.jpg',
      'CC BY 4.0',
      'Wikimedia Commons',
      'Batik Khas Pekalongan.jpg',
      'https://commons.wikimedia.org/wiki/File:Batik_Khas_Pekalongan.jpg',
      'Sekar Jarwo Soekarno',
      'https://creativecommons.org/licenses/by/4.0/',
      'CC BY 4.0'
    )
)
INSERT INTO content_items (
  owner_id,
  content_type,
  slug,
  title,
  summary,
  body,
  pricing_mode,
  price_cents,
  price_unit,
  original_price_cents,
  seller_type,
  minimum_order,
  promo_label,
  promo_start_at,
  promo_end_at,
  currency,
  tags,
  cover_image,
  category,
  content_status,
  rating,
  review_count,
  listing_intent,
  listing_status,
  completion_percentage,
  last_saved_at,
  published_at,
  attributes,
  contact_snapshot,
  metadata,
  created_at,
  updated_at
)
SELECT
  '00000000-0000-0000-0000-000000000801',
  content_type,
  slug,
  title,
  summary,
  body,
  'fixed',
  NULL,
  price_unit,
  NULL,
  'open_data_reference',
  NULL,
  NULL,
  NULL,
  NULL,
  'IDR',
  tags,
  cover_image,
  category,
  'active',
  0,
  0,
  NULL,
  'published',
  100,
  NOW(),
  NOW() - INTERVAL '1 hour',
  jsonb_strip_nulls(
    jsonb_build_object(
      'record_kind', 'real_open_data_reference',
      'source_url', source_url,
      'source_title', source_title,
      'city', city,
      'latitude', lat,
      'longitude', lng
    )
  ),
  '{}'::jsonb,
  jsonb_strip_nulls(
    jsonb_build_object(
      'seed_pack', 'real_indonesia_open_data_20260723',
      'record_kind', 'real_open_data_reference',
      'is_transactional', false,
      'contact_policy', 'no_private_contact_seeded',
      'market_side', 'reference',
      'listing_side', 'reference',
      'listing_mode', 'source_reference',
      'create_category', create_category,
      'business_discovery_category', create_category,
      'marketplace_category_slug', marketplace_category_slug,
      'city', city,
      'location', location_text,
      'latitude', lat,
      'longitude', lng,
      'source', jsonb_build_object(
        'title', source_title,
        'url', source_url,
        'license', source_license,
        'access', 'public'
      ),
      'source_url', source_url,
      'source_title', source_title,
      'cover_image', cover_image,
      'image_url', cover_image,
      'image_urls', jsonb_build_array(cover_image),
      'gallery_images', jsonb_build_array(cover_image),
      'image_credit', jsonb_build_object(
        'provider', media_provider,
        'title', media_title,
        'source_url', media_source_url,
        'author', media_author,
        'license_url', media_license_url,
        'license', media_license_name,
        'note', 'Free/public media reference. Keep attribution when reusing.'
      ),
      'trust_note', 'Real public reference data only. No availability, pricing, verification, or private contact is implied.'
    )
  ),
  NOW() - INTERVAL '1 hour',
  NOW()
FROM real_items
-- Keep the static seed strict: no generic illustration rows.
-- Only records whose external media is the actual subject of the row are inserted.
WHERE cover_image LIKE 'https://commons.wikimedia.org/%'
  AND slug IN (
    'pasar-beringharjo-yogyakarta-open-data',
    'pasar-tanah-abang-jakarta-open-data',
    'pasar-klewer-surakarta-open-data',
    'kampung-batik-laweyan-surakarta-open-data',
    'pasar-terapung-lok-baintan-banjar-open-data',
    'batik-pekalongan-referensi-media-bebas'
  )
ON CONFLICT (slug) DO UPDATE
SET owner_id = EXCLUDED.owner_id,
    content_type = EXCLUDED.content_type,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    body = EXCLUDED.body,
    pricing_mode = EXCLUDED.pricing_mode,
    price_cents = EXCLUDED.price_cents,
    price_unit = EXCLUDED.price_unit,
    original_price_cents = EXCLUDED.original_price_cents,
    seller_type = EXCLUDED.seller_type,
    minimum_order = EXCLUDED.minimum_order,
    promo_label = EXCLUDED.promo_label,
    promo_start_at = EXCLUDED.promo_start_at,
    promo_end_at = EXCLUDED.promo_end_at,
    currency = EXCLUDED.currency,
    tags = EXCLUDED.tags,
    cover_image = EXCLUDED.cover_image,
    category = EXCLUDED.category,
    content_status = EXCLUDED.content_status,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    listing_intent = EXCLUDED.listing_intent,
    listing_status = EXCLUDED.listing_status,
    completion_percentage = EXCLUDED.completion_percentage,
    last_saved_at = EXCLUDED.last_saved_at,
    published_at = EXCLUDED.published_at,
    attributes = EXCLUDED.attributes,
    contact_snapshot = EXCLUDED.contact_snapshot,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

WITH real_service_items (
  slug,
  title,
  summary,
  body,
  price_cents,
  price_unit,
  price_label,
  tags,
  cover_image,
  city,
  location_text,
  lat,
  lng,
  marketplace_subcategory_slug,
  service_mode,
  source_title,
  source_url,
  source_license,
  media_title,
  media_source_url,
  media_author,
  media_license_url,
  media_license_name,
  search_text
) AS (
  VALUES
    (
      'oss-nib-legalitas-usaha-layanan-publik',
      'Jasa usaha: OSS NIB dan legalitas usaha resmi',
      'Rujukan layanan publik untuk membuat dan mengelola NIB melalui OSS berbasis risiko. Cocok untuk pelaku usaha yang ingin memahami langkah legalitas sebelum jualan lebih luas.',
      'OSS menerbitkan Nomor Induk Berusaha sebagai identitas pelaku usaha. Rujukan ini diarahkan ke sumber resmi pemerintah; tidak ada nomor pribadi atau agen tidak terverifikasi yang disimpan di seed.',
      0,
      'service',
      'Gratis sesuai standar layanan resmi',
      ARRAY['jasa usaha','legalitas usaha','NIB','OSS','perizinan usaha','UMKM','layanan publik'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Jalan-jalan_ke_Pasar_Beringharjo-12.jpg?width=1200',
      'Jakarta',
      'Layanan nasional melalui OSS RBA',
      -6.1753942,
      106.827183,
      'legal-finance',
      'online',
      'Standar Pelayanan Penerbitan NIB di Sistem OSS',
      'https://www.investindonesia.go.id/id/info/pengumuman/standar-pelayanan-penerbitan-nib-di-sistem-oss',
      'Public government information reference',
      'Jalan-jalan ke Pasar Beringharjo',
      'https://commons.wikimedia.org/wiki/File:Jalan-jalan_ke_Pasar_Beringharjo-12.jpg',
      'Indonesiagood',
      'https://creativecommons.org/licenses/by/3.0/deed.en',
      'CC BY 3.0',
      'jasa usaha jasa legalitas usaha jasa perizinan OSS NIB pendirian usaha UMKM layanan publik legal finance'
    ),
    (
      'bps-pst-konsultasi-statistik-usaha',
      'Jasa usaha: konsultasi statistik dan data pasar BPS',
      'Pintu rujukan untuk pelaku usaha yang butuh data wilayah, data industri, atau konsultasi statistik sebelum membuka cabang, mencari supplier, atau membaca pasar lokal.',
      'Pelayanan Statistik Terpadu BPS menyediakan perpustakaan, konsultasi statistik, rekomendasi kegiatan statistik, dan akses data resmi. Data ini berguna untuk validasi lokasi dan ukuran pasar.',
      0,
      'service',
      'Gratis untuk layanan informasi tertentu',
      ARRAY['jasa usaha','konsultasi statistik','riset pasar','data usaha','BPS','WebAPI','UMKM'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Pasar_Klewer_Solo.JPG?width=1200',
      'Jakarta',
      'Pelayanan Statistik Terpadu BPS',
      -6.1744651,
      106.822745,
      'consulting',
      'online',
      'Pelayanan Statistik Terpadu BPS',
      'https://pst.bps.go.id/',
      'Public government information reference',
      'Pasar Klewer Solo',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer_Solo.JPG',
      'Gombang',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer_Solo.JPG',
      'Public domain',
      'jasa usaha konsultasi statistik riset pasar data usaha BPS WebAPI rekomendasi kegiatan statistik konsultan UMKM'
    ),
    (
      'djki-pangkalan-data-kekayaan-intelektual',
      'Jasa usaha: cek merek dan kekayaan intelektual DJKI',
      'Rujukan resmi untuk pengecekan merek, paten, desain industri, hak cipta, dan indikasi geografis sebelum pelaku usaha memakai nama produk atau identitas brand.',
      'DJKI menyediakan akses informasi kekayaan intelektual. Seed ini hanya memberi jalur rujukan sumber resmi agar pemilik usaha tidak salah mengira data brand sebagai layanan calo.',
      NULL,
      'reference',
      'Biaya mengikuti ketentuan resmi DJKI',
      ARRAY['jasa usaha','merek','hak cipta','paten','desain industri','HKI','legalitas brand'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Batik_Khas_Pekalongan.jpg?width=1200',
      'Jakarta',
      'Direktorat Jenderal Kekayaan Intelektual',
      -6.211544,
      106.845172,
      'legal-finance',
      'online',
      'Direktorat Jenderal Kekayaan Intelektual',
      'https://www.dgip.go.id/',
      'Public government information reference',
      'Batik Khas Pekalongan',
      'https://commons.wikimedia.org/wiki/File:Batik_Khas_Pekalongan.jpg',
      'Sekar Jarwo Soekarno',
      'https://creativecommons.org/licenses/by/4.0/deed.en',
      'CC BY 4.0',
      'jasa usaha hak kekayaan intelektual merek hak cipta paten desain industri indikasi geografis legal finance UMKM'
    ),
    (
      'smesco-inkubasi-pelatihan-umkm',
      'Jasa usaha: inkubasi, pelatihan, dan business matching SMESCO',
      'Rujukan layanan pendampingan UMKM dari SMESCO untuk pelatihan, konsultasi, akses pasar, business matching, dan penguatan kapasitas usaha.',
      'SMESCO adalah lembaga resmi di bawah Kementerian Koperasi dan UKM. Seed ini menampilkan rujukan layanan, bukan klaim ketersediaan slot atau koneksi langsung.',
      NULL,
      'reference',
      'Ikuti program dan ketentuan SMESCO',
      ARRAY['jasa usaha','inkubasi','pelatihan UMKM','business matching','konsultasi bisnis','akses pasar'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Jalan-jalan_ke_Pasar_Beringharjo-12.jpg?width=1200',
      'Jakarta',
      'SMESCO Indonesia',
      -6.23827,
      106.83118,
      'consulting',
      'hybrid',
      'SMESCO Indonesia',
      'https://smesco.go.id/',
      'Public web reference',
      'Jalan-jalan ke Pasar Beringharjo',
      'https://commons.wikimedia.org/wiki/File:Jalan-jalan_ke_Pasar_Beringharjo-12.jpg',
      'Indonesiagood',
      'https://creativecommons.org/licenses/by/3.0/deed.en',
      'CC BY 3.0',
      'jasa usaha inkubasi pelatihan UMKM business matching konsultasi pemasaran akses pasar mentoring SMESCO'
    ),
    (
      'smesco-fulfillment-logistik-umkm',
      'Jasa usaha: fulfillment dan logistik UMKM SMESCO',
      'Rujukan layanan pendukung operasional untuk pelaku UMKM yang butuh fulfillment, distribusi, dan pengelolaan alur produk.',
      'Layanan logistik dan fulfillment membantu UMKM mengatur produk dari penyimpanan sampai pengiriman. Gunakan sumber resmi untuk melihat program yang sedang tersedia.',
      NULL,
      'reference',
      'Ikuti program dan ketentuan SMESCO',
      ARRAY['jasa usaha','jasa logistik','fulfillment','distribusi produk','operasional UMKM','SMESCO'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Pasar_Klewer_Solo.JPG?width=1200',
      'Jakarta',
      'SMESCO Indonesia',
      -6.23827,
      106.83118,
      'logistics',
      'hybrid',
      'SMESCO Indonesia',
      'https://smesco.go.id/',
      'Public web reference',
      'Pasar Klewer Solo',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer_Solo.JPG',
      'Gombang',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer_Solo.JPG',
      'Public domain',
      'jasa usaha jasa logistik fulfillment distribusi produk gudang operasional UMKM SMESCO supplier'
    ),
    (
      'smesco-branding-umkm-referensi-layanan',
      'Jasa usaha: branding, kemasan, dan penguatan produk UMKM',
      'Rujukan layanan branding dan penguatan produk UMKM dari SMESCO, cocok untuk usaha yang ingin merapikan identitas, kemasan, dan materi jualan.',
      'Branding membantu produk UMKM lebih mudah dikenali di kanal offline dan online. Seed ini memakai sumber resmi sebagai referensi dan tidak menyimpan kontak pribadi.',
      NULL,
      'reference',
      'Ikuti program dan ketentuan SMESCO',
      ARRAY['jasa usaha','jasa desain kreatif','branding','kemasan produk','desain UMKM','SMESCO'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Batik_Khas_Pekalongan.jpg?width=1200',
      'Jakarta',
      'SMESCO Indonesia',
      -6.23827,
      106.83118,
      'creative',
      'hybrid',
      'SMESCO Indonesia',
      'https://smesco.go.id/',
      'Public web reference',
      'Batik Khas Pekalongan',
      'https://commons.wikimedia.org/wiki/File:Batik_Khas_Pekalongan.jpg',
      'Sekar Jarwo Soekarno',
      'https://creativecommons.org/licenses/by/4.0/deed.en',
      'CC BY 4.0',
      'jasa usaha jasa desain kreatif branding kemasan produk desain UMKM co branding rebranding SMESCO'
    ),
    (
      'smesco-digitalisasi-umkm-referensi-layanan',
      'Jasa usaha: digitalisasi UMKM dan akses pasar online',
      'Rujukan layanan digitalisasi UMKM dari SMESCO untuk pelaku usaha yang ingin merapikan kehadiran digital, membaca pasar, dan memperluas kanal jualan.',
      'Digitalisasi UMKM dapat mencakup pendampingan katalog, kanal online, marketplace, dan market intelligence. Ketersediaan program mengikuti informasi resmi SMESCO.',
      NULL,
      'reference',
      'Ikuti program dan ketentuan SMESCO',
      ARRAY['jasa usaha','jasa digital','digitalisasi UMKM','marketplace','market intelligence','akses pasar online'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Jalan-jalan_ke_Pasar_Beringharjo-12.jpg?width=1200',
      'Jakarta',
      'SMESCO Indonesia',
      -6.23827,
      106.83118,
      'digital',
      'online',
      'SMESCO Indonesia',
      'https://smesco.go.id/',
      'Public web reference',
      'Jalan-jalan ke Pasar Beringharjo',
      'https://commons.wikimedia.org/wiki/File:Jalan-jalan_ke_Pasar_Beringharjo-12.jpg',
      'Indonesiagood',
      'https://creativecommons.org/licenses/by/3.0/deed.en',
      'CC BY 3.0',
      'jasa usaha jasa digital teknologi digitalisasi UMKM marketplace market intelligence akses pasar online SMESCO'
    ),
    (
      'bpjph-sehati-sertifikasi-halal-umk-2026',
      'Jasa usaha: sertifikasi halal gratis SEHATI untuk UMK',
      'Rujukan program sertifikasi halal gratis BPJPH untuk pelaku UMK yang memenuhi kriteria program SEHATI 2026.',
      'Program SEHATI memiliki kuota dan syarat. Seed ini membantu pengguna menemukan jalur resmi BPJPH, bukan menjanjikan kelulusan atau menghubungkan ke pendamping tertentu.',
      0,
      'program',
      'Gratis jika memenuhi syarat program',
      ARRAY['jasa usaha','sertifikasi halal','BPJPH','SEHATI','UMK','legalitas produk','NIB'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Indonesian_coffee_beans.jpg?width=1200',
      'Jakarta',
      'Badan Penyelenggara Jaminan Produk Halal',
      -6.208763,
      106.845599,
      'legal-finance',
      'online',
      'Kriteria Pelaku UMK Program SEHATI 2026',
      'https://bpjph.halal.go.id/read/ini-kriteria-pelaku-umk-yang-dapat-mengajukan-sertifikat-halal-gratis-program-sehati-2026',
      'Public government information reference',
      'Indonesian coffee beans',
      'https://commons.wikimedia.org/wiki/File:Indonesian_coffee_beans.jpg',
      'Abdulrohmatt',
      'https://creativecommons.org/licenses/by-sa/4.0/deed.en',
      'CC BY-SA 4.0',
      'jasa usaha sertifikasi halal BPJPH SEHATI UMK self declare NIB legalitas produk makanan minuman'
    ),
    (
      'legalitas-smesco-badan-usaha-umkm',
      'Jasa usaha: legalitas badan usaha dan dokumen bisnis UMKM',
      'Rujukan layanan legalitas SMESCO untuk kebutuhan seperti pendirian badan usaha, NIB, NPWP, OSS, virtual office, halal, dan HKI merek.',
      'Layanan legalitas perlu dicek langsung ke sumber resmi karena biaya, paket, dan syarat dapat berubah. Seed tidak menyimpan nomor kontak pribadi dan tidak bertindak sebagai agen.',
      NULL,
      'reference',
      'Cek biaya dan syarat di situs resmi',
      ARRAY['jasa usaha','legalitas usaha','PT Perorangan','NPWP','OSS','NIB','HKI merek','sertifikasi halal'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Batik_Khas_Pekalongan.jpg?width=1200',
      'Jakarta',
      'SMESCO Legalitas',
      -6.23827,
      106.83118,
      'legal-finance',
      'online',
      'SMESCO Legalitas',
      'https://legalitas.smesco.go.id/',
      'Public web reference',
      'Batik Khas Pekalongan',
      'https://commons.wikimedia.org/wiki/File:Batik_Khas_Pekalongan.jpg',
      'Sekar Jarwo Soekarno',
      'https://creativecommons.org/licenses/by/4.0/deed.en',
      'CC BY 4.0',
      'jasa usaha legalitas usaha badan usaha PT Perorangan NPWP OSS NIB virtual office HKI merek sertifikasi halal SMESCO'
    )
)
INSERT INTO content_items (
  owner_id,
  content_type,
  slug,
  title,
  summary,
  body,
  pricing_mode,
  price_cents,
  price_unit,
  original_price_cents,
  seller_type,
  minimum_order,
  promo_label,
  promo_start_at,
  promo_end_at,
  currency,
  tags,
  cover_image,
  category,
  content_status,
  rating,
  review_count,
  marketplace_category_id,
  marketplace_subcategory_id,
  listing_intent,
  listing_status,
  completion_percentage,
  last_saved_at,
  published_at,
  attributes,
  contact_snapshot,
  metadata,
  created_at,
  updated_at
)
SELECT
  '00000000-0000-0000-0000-000000000801',
  'service',
  slug,
  title,
  summary,
  body,
  'fixed',
  price_cents,
  price_unit,
  NULL,
  'public_service_reference',
  NULL,
  NULL,
  NULL,
  NULL,
  'IDR',
  tags,
  cover_image,
  'service',
  'active',
  0,
  0,
  (SELECT id FROM marketplace_categories WHERE slug = 'services' LIMIT 1),
  (
    SELECT ms.id
    FROM marketplace_subcategories ms
    JOIN marketplace_categories mc ON mc.id = ms.category_id
    WHERE mc.slug = 'services'
      AND ms.slug = marketplace_subcategory_slug
    LIMIT 1
  ),
  NULL,
  'published',
  100,
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day',
  jsonb_build_object(
    'seed_pack', 'real_indonesia_open_data_20260723',
    'record_kind', 'real_public_service_reference',
    'source_title', source_title,
    'source_url', source_url,
    'source_license', source_license,
    'source_verified_at', '2026-07-23',
    'category_slug', 'services',
    'subcategory_slug', marketplace_subcategory_slug,
    'service_mode', service_mode,
    'price_label', price_label
  ),
  jsonb_build_object(
    'source_only', true,
    'contact_policy', 'no_private_contact_seeded',
    'official_source_url', source_url
  ),
  jsonb_build_object(
    'seed_pack', 'real_indonesia_open_data_20260723',
    'record_kind', 'real_public_service_reference',
    'is_transactional', false,
    'market_side', 'supply',
    'listing_side', 'supply',
    'listing_mode', 'source_reference',
    'create_category', 'service',
    'business_discovery_category', 'service',
    'marketplace_category_slug', 'services',
    'marketplace_subcategory_slug', marketplace_subcategory_slug,
    'subcategory', marketplace_subcategory_slug,
    'sub_category', marketplace_subcategory_slug,
    'service_mode', service_mode,
    'work_mode', service_mode,
    'city', city,
    'location', location_text,
    'latitude', lat,
    'longitude', lng,
    'price_label', price_label,
    'source_title', source_title,
    'source_url', source_url,
    'source_license', source_license,
    'source_verified_at', '2026-07-23',
    'source', jsonb_build_object(
      'title', source_title,
      'url', source_url,
      'license', source_license,
      'verified_at', '2026-07-23'
    ),
    'search_text', search_text,
    'cover_image', cover_image,
    'image_url', cover_image,
    'media_provider', 'Wikimedia Commons',
    'media_title', media_title,
    'media_source_url', media_source_url,
    'media_author', media_author,
    'media_license_url', media_license_url,
    'media_license_name', media_license_name,
    'image_credit', jsonb_build_object(
      'title', media_title,
      'source_url', media_source_url,
      'author', media_author,
      'license_url', media_license_url,
      'license_name', media_license_name
    ),
    'contact_policy', 'no_private_contact_seeded',
    'trust_note', 'Rujukan layanan publik/kelembagaan dari sumber resmi. Verifikasi syarat, biaya, dan ketersediaan di situs sumber.'
  ),
  NOW() - INTERVAL '1 day',
  NOW()
FROM real_service_items
-- Service references in this CTE do not carry source-specific photos yet, so they are held back.
WHERE source_url = media_source_url
ON CONFLICT (slug) DO UPDATE
SET owner_id = EXCLUDED.owner_id,
    content_type = EXCLUDED.content_type,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    body = EXCLUDED.body,
    pricing_mode = EXCLUDED.pricing_mode,
    price_cents = EXCLUDED.price_cents,
    price_unit = EXCLUDED.price_unit,
    original_price_cents = EXCLUDED.original_price_cents,
    seller_type = EXCLUDED.seller_type,
    minimum_order = EXCLUDED.minimum_order,
    promo_label = EXCLUDED.promo_label,
    promo_start_at = EXCLUDED.promo_start_at,
    promo_end_at = EXCLUDED.promo_end_at,
    currency = EXCLUDED.currency,
    tags = EXCLUDED.tags,
    cover_image = EXCLUDED.cover_image,
    category = EXCLUDED.category,
    content_status = EXCLUDED.content_status,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    marketplace_category_id = EXCLUDED.marketplace_category_id,
    marketplace_subcategory_id = EXCLUDED.marketplace_subcategory_id,
    listing_intent = EXCLUDED.listing_intent,
    listing_status = EXCLUDED.listing_status,
    completion_percentage = EXCLUDED.completion_percentage,
    last_saved_at = EXCLUDED.last_saved_at,
    published_at = EXCLUDED.published_at,
    attributes = EXCLUDED.attributes,
    contact_snapshot = EXCLUDED.contact_snapshot,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

WITH real_explore_items (
  slug,
  content_type,
  title,
  summary,
  body,
  price_unit,
  price_label,
  tags,
  cover_image,
  category,
  create_category,
  marketplace_category_slug,
  marketplace_subcategory_slug,
  city,
  location_text,
  lat,
  lng,
  source_title,
  source_url,
  source_license,
  media_title,
  media_source_url,
  media_author,
  media_license_url,
  media_license_name,
  search_text
) AS (
  VALUES
    (
      'kemenperin-restrukturisasi-mesin-ikm',
      'product',
      'Mesin & alat usaha: restrukturisasi mesin IKM Kemenperin',
      'Rujukan program Kemenperin untuk modernisasi mesin dan peralatan IKM. Cocok untuk pelaku usaha yang sedang membandingkan kebutuhan alat produksi.',
      'Program restrukturisasi mesin/peralatan IKM adalah referensi resmi untuk memahami dukungan modernisasi alat produksi. Seed ini bukan klaim stok mesin atau vendor tertentu.',
      'reference',
      'Cek syarat program di sumber resmi',
      ARRAY['mesin alat usaha','mesin produksi','peralatan usaha','IKM','Kemenperin','modernisasi alat'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Industrial_sewing_machine.jpg?width=1200',
      'equipment',
      'equipment',
      'machines-tools',
      'production-machines',
      'Indonesia',
      'Program nasional Kementerian Perindustrian',
      NULL,
      NULL,
      'Restrukturisasi Mesin dan/atau Peralatan IKM',
      'https://imc.kemenperin.go.id/infografis/restrukturisasi-mesin-atau-peralatan-untuk-pelaku-ikm',
      'Public government information reference',
      'Industrial sewing machine',
      'https://commons.wikimedia.org/wiki/File:Industrial_sewing_machine.jpg',
      'Haddybellz',
      'https://creativecommons.org/licenses/by-sa/4.0/deed.en',
      'CC BY-SA 4.0',
      'mesin alat usaha mesin produksi peralatan usaha restrukturisasi mesin IKM Kemenperin alat produksi modernisasi'
    ),
    (
      'sirup-lkpp-rujukan-pengadaan-mesin-alat',
      'product',
      'Mesin & alat usaha: rujukan pengadaan alat di SiRUP LKPP',
      'Rujukan SiRUP LKPP untuk membaca rencana pengadaan barang/jasa pemerintah, termasuk kata kunci mesin, alat, peralatan kantor, dan perlengkapan operasional.',
      'SiRUP membantu pelaku usaha melihat rencana pengadaan secara terbuka. Data ini dipakai sebagai referensi peluang dan kategori alat, bukan sebagai transaksi langsung di Lajukan.',
      'reference',
      'Lihat paket dan jadwal di SiRUP',
      ARRAY['mesin alat usaha','pengadaan alat','LKPP','SiRUP','peralatan kantor','perlengkapan usaha'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Jalan-jalan_ke_Pasar_Beringharjo-12.jpg?width=1200',
      'equipment',
      'equipment',
      'machines-tools',
      'office-equipment',
      'Indonesia',
      'Sistem Informasi Rencana Umum Pengadaan LKPP',
      NULL,
      NULL,
      'SiRUP LKPP',
      'https://sirup.lkpp.go.id/sirup/',
      'Public government procurement reference',
      'Jalan-jalan ke Pasar Beringharjo',
      'https://commons.wikimedia.org/wiki/File:Jalan-jalan_ke_Pasar_Beringharjo-12.jpg',
      'Indonesiagood',
      'https://creativecommons.org/licenses/by/3.0/deed.en',
      'CC BY 3.0',
      'mesin alat usaha pengadaan alat peralatan usaha LKPP SiRUP rencana umum pengadaan perlengkapan operasional'
    ),
    (
      'kemenperin-peralatan-ikm-makanan-minuman',
      'product',
      'Mesin & alat usaha: referensi peralatan IKM makanan minuman',
      'Rujukan Kemenperin untuk pelaku IKM makanan minuman yang membutuhkan konteks mesin, alat pengolahan, dan peningkatan kapasitas produksi.',
      'Data ini membantu pengguna memahami kata kunci mesin produksi untuk usaha makanan dan minuman. Seed tidak menampilkan vendor, nomor kontak, atau harga mesin yang tidak diverifikasi.',
      'reference',
      'Gunakan sebagai rujukan kategori alat',
      ARRAY['mesin alat usaha','mesin makanan','alat pengolahan','IKM pangan','Kemenperin','usaha makanan minuman'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Indonesian_coffee_beans.jpg?width=1200',
      'equipment',
      'equipment',
      'machines-tools',
      'food-beverage-machines',
      'Indonesia',
      'Kementerian Perindustrian',
      NULL,
      NULL,
      'Satu Data Kemenperin - IKM PFBB Restrukturisasi Mesin',
      'https://satudata.kemenperin.go.id/tr/dataset/jumlah-ikm-pfbb-program-restruk-mesin',
      'Public government information reference',
      'Indonesian coffee beans',
      'https://commons.wikimedia.org/wiki/File:Indonesian_coffee_beans.jpg',
      'Abdulrohmatt',
      'https://creativecommons.org/licenses/by-sa/4.0/deed.en',
      'CC BY-SA 4.0',
      'mesin alat usaha mesin makanan minuman alat pengolahan IKM pangan Kemenperin peralatan produksi'
    ),
    (
      'lkpp-ekatalog-peluang-pasar-umkk',
      'business_transfer',
      'Peluang usaha: UMKK masuk pasar pengadaan lewat e-Katalog',
      'Rujukan peluang pasar pengadaan pemerintah untuk UMKK melalui kanal LKPP dan e-Katalog. Cocok untuk usaha yang ingin membaca peluang B2G secara hati-hati.',
      'LKPP mendorong transaksi produk dalam negeri dan pelibatan UMKK di pengadaan pemerintah. Seed ini tidak membuat penawaran kemitraan palsu; pengguna diarahkan ke sumber resmi.',
      'reference',
      'Cek ketentuan dan katalog resmi',
      ARRAY['peluang usaha franchise kemitraan reseller','pengadaan pemerintah','UMKK','LKPP','e-Katalog','kemitraan usaha'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Pasar_Klewer_Solo.JPG?width=1200',
      'opportunity',
      'opportunity',
      'business-opportunities',
      'partnerships',
      'Indonesia',
      'LKPP dan e-Katalog',
      NULL,
      NULL,
      'LKPP',
      'https://lkpp.go.id/read/bu/platform-katalog-elektronik-langkah-strategis-lkpp-optimalkan-pdn-dan-berdayakan',
      'Public government information reference',
      'Pasar Klewer Solo',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer_Solo.JPG',
      'Gombang',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer_Solo.JPG',
      'Public domain',
      'peluang usaha franchise kemitraan reseller pengadaan pemerintah UMKK LKPP e-Katalog katalog elektronik pasar pemerintah'
    ),
    (
      'data-lkpp-pencadangan-paket-usaha-mikro-kecil',
      'business_transfer',
      'Peluang usaha: data pencadangan paket untuk usaha mikro kecil',
      'Rujukan data LKPP tentang pencadangan paket pengadaan bagi usaha mikro dan kecil. Berguna untuk membaca sektor dan pola peluang, bukan sebagai daftar tender final.',
      'Pencadangan paket membantu UMK melihat ruang masuk ke pasar pengadaan. Verifikasi paket, jadwal, dan syarat harus tetap dilakukan di sistem resmi LKPP.',
      'reference',
      'Gunakan sebagai data riset peluang',
      ARRAY['peluang usaha franchise kemitraan reseller','usaha mikro kecil','pengadaan pemerintah','data LKPP','UMK','kemitraan'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Jalan-jalan_ke_Pasar_Beringharjo-12.jpg?width=1200',
      'opportunity',
      'opportunity',
      'business-opportunities',
      'partnerships',
      'Indonesia',
      'Open data LKPP',
      NULL,
      NULL,
      'Open Data LKPP - Pencadangan Paket Usaha Mikro dan Kecil',
      'https://data.lkpp.go.id/tr/dataset/nilai-pencadangan-paket-usaha-mikro-dan-kecil-dalam-perencanaan-pengadaan-barang-jasa',
      'Public open-data reference',
      'Jalan-jalan ke Pasar Beringharjo',
      'https://commons.wikimedia.org/wiki/File:Jalan-jalan_ke_Pasar_Beringharjo-12.jpg',
      'Indonesiagood',
      'https://creativecommons.org/licenses/by/3.0/deed.en',
      'CC BY 3.0',
      'peluang usaha franchise kemitraan reseller usaha mikro kecil UMK pencadangan paket pengadaan pemerintah data LKPP'
    ),
    (
      'oss-kbli-perdagangan-reseller-distributor',
      'business_transfer',
      'Peluang usaha: riset KBLI perdagangan untuk reseller dan distributor',
      'Rujukan OSS/KBLI untuk memahami klasifikasi usaha perdagangan sebelum menjalankan reseller, distributor, atau kemitraan penjualan.',
      'KBLI membantu pelaku usaha memilih klasifikasi kegiatan usaha saat mengurus legalitas. Seed ini dipakai sebagai rujukan riset peluang dan legalitas, bukan paket franchise.',
      'reference',
      'Gunakan untuk riset legalitas peluang',
      ARRAY['peluang usaha franchise kemitraan reseller','KBLI','OSS','reseller','distributor','perdagangan besar','legalitas usaha'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Batik_Khas_Pekalongan.jpg?width=1200',
      'opportunity',
      'opportunity',
      'business-opportunities',
      'reseller',
      'Indonesia',
      'OSS RBA dan KBLI',
      NULL,
      NULL,
      'OSS RBA',
      'https://oss.go.id/',
      'Public government information reference',
      'Batik Khas Pekalongan',
      'https://commons.wikimedia.org/wiki/File:Batik_Khas_Pekalongan.jpg',
      'Sekar Jarwo Soekarno',
      'https://creativecommons.org/licenses/by/4.0/deed.en',
      'CC BY 4.0',
      'peluang usaha franchise kemitraan reseller KBLI OSS perdagangan besar perdagangan eceran distributor legalitas usaha'
    ),
    (
      'smesco-business-matching-kemitraan-umkm',
      'business_transfer',
      'Peluang usaha: business matching dan kemitraan UMKM SMESCO',
      'Rujukan SMESCO untuk business matching, akses pasar, konsultasi, dan penguatan jejaring UMKM yang mencari mitra usaha.',
      'Business matching dapat membantu UMKM bertemu calon pembeli, kanal distribusi, atau mitra program. Informasi jadwal dan ketersediaan harus dicek ke SMESCO.',
      'reference',
      'Ikuti program dan ketentuan SMESCO',
      ARRAY['peluang usaha franchise kemitraan reseller','business matching','SMESCO','kemitraan UMKM','akses pasar','reseller'],
      'https://commons.wikimedia.org/wiki/Special:FilePath/Pasar_Klewer_Solo.JPG?width=1200',
      'opportunity',
      'opportunity',
      'business-opportunities',
      'partnerships',
      'Jakarta',
      'SMESCO Indonesia',
      -6.23827,
      106.83118,
      'SMESCO Indonesia',
      'https://smesco.go.id/',
      'Public web reference',
      'Pasar Klewer Solo',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer_Solo.JPG',
      'Gombang',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer_Solo.JPG',
      'Public domain',
      'peluang usaha franchise kemitraan reseller business matching SMESCO kemitraan UMKM akses pasar jaringan usaha'
    )
)
INSERT INTO content_items (
  owner_id,
  content_type,
  slug,
  title,
  summary,
  body,
  pricing_mode,
  price_cents,
  price_unit,
  original_price_cents,
  seller_type,
  minimum_order,
  promo_label,
  promo_start_at,
  promo_end_at,
  currency,
  tags,
  cover_image,
  category,
  content_status,
  rating,
  review_count,
  marketplace_category_id,
  marketplace_subcategory_id,
  listing_intent,
  listing_status,
  completion_percentage,
  last_saved_at,
  published_at,
  attributes,
  contact_snapshot,
  metadata,
  created_at,
  updated_at
)
SELECT
  '00000000-0000-0000-0000-000000000801',
  content_type,
  slug,
  title,
  summary,
  body,
  'fixed',
  NULL,
  price_unit,
  NULL,
  'public_reference',
  NULL,
  NULL,
  NULL,
  NULL,
  'IDR',
  tags,
  cover_image,
  category,
  'active',
  0,
  0,
  (SELECT id FROM marketplace_categories WHERE slug = marketplace_category_slug LIMIT 1),
  (
    SELECT ms.id
    FROM marketplace_subcategories ms
    JOIN marketplace_categories mc ON mc.id = ms.category_id
    WHERE mc.slug = marketplace_category_slug
      AND ms.slug = marketplace_subcategory_slug
    LIMIT 1
  ),
  NULL,
  'published',
  100,
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '1 day',
  jsonb_build_object(
    'seed_pack', 'real_indonesia_open_data_20260723',
    'record_kind', 'real_public_reference',
    'source_title', source_title,
    'source_url', source_url,
    'source_license', source_license,
    'source_verified_at', '2026-07-23',
    'category_slug', marketplace_category_slug,
    'subcategory_slug', marketplace_subcategory_slug,
    'price_label', price_label
  ),
  jsonb_build_object(
    'source_only', true,
    'contact_policy', 'no_private_contact_seeded',
    'official_source_url', source_url
  ),
  jsonb_build_object(
    'seed_pack', 'real_indonesia_open_data_20260723',
    'record_kind', 'real_public_reference',
    'is_transactional', false,
    'market_side', 'supply',
    'listing_side', 'supply',
    'listing_mode', 'source_reference',
    'create_category', create_category,
    'business_discovery_category', create_category,
    'marketplace_category_slug', marketplace_category_slug,
    'marketplace_subcategory_slug', marketplace_subcategory_slug,
    'subcategory', marketplace_subcategory_slug,
    'sub_category', marketplace_subcategory_slug,
    'city', city,
    'location', location_text,
    'latitude', lat,
    'longitude', lng,
    'price_label', price_label,
    'source_title', source_title,
    'source_url', source_url,
    'source_license', source_license,
    'source_verified_at', '2026-07-23',
    'source', jsonb_build_object(
      'title', source_title,
      'url', source_url,
      'license', source_license,
      'verified_at', '2026-07-23'
    ),
    'search_text', search_text,
    'cover_image', cover_image,
    'image_url', cover_image,
    'media_provider', 'Wikimedia Commons',
    'media_title', media_title,
    'media_source_url', media_source_url,
    'media_author', media_author,
    'media_license_url', media_license_url,
    'media_license_name', media_license_name,
    'image_credit', jsonb_build_object(
      'title', media_title,
      'source_url', media_source_url,
      'author', media_author,
      'license_url', media_license_url,
      'license_name', media_license_name
    ),
    'contact_policy', 'no_private_contact_seeded',
    'trust_note', 'Rujukan publik dari sumber resmi/terbuka. Verifikasi syarat, biaya, jadwal, dan ketersediaan di situs sumber.'
  ),
  NOW() - INTERVAL '1 day',
  NOW()
FROM real_explore_items
-- Explore references in this CTE do not carry source-specific photos yet, so they are held back.
WHERE source_url = media_source_url
ON CONFLICT (slug) DO UPDATE
SET owner_id = EXCLUDED.owner_id,
    content_type = EXCLUDED.content_type,
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    body = EXCLUDED.body,
    pricing_mode = EXCLUDED.pricing_mode,
    price_cents = EXCLUDED.price_cents,
    price_unit = EXCLUDED.price_unit,
    original_price_cents = EXCLUDED.original_price_cents,
    seller_type = EXCLUDED.seller_type,
    minimum_order = EXCLUDED.minimum_order,
    promo_label = EXCLUDED.promo_label,
    promo_start_at = EXCLUDED.promo_start_at,
    promo_end_at = EXCLUDED.promo_end_at,
    currency = EXCLUDED.currency,
    tags = EXCLUDED.tags,
    cover_image = EXCLUDED.cover_image,
    category = EXCLUDED.category,
    content_status = EXCLUDED.content_status,
    rating = EXCLUDED.rating,
    review_count = EXCLUDED.review_count,
    marketplace_category_id = EXCLUDED.marketplace_category_id,
    marketplace_subcategory_id = EXCLUDED.marketplace_subcategory_id,
    listing_intent = EXCLUDED.listing_intent,
    listing_status = EXCLUDED.listing_status,
    completion_percentage = EXCLUDED.completion_percentage,
    last_saved_at = EXCLUDED.last_saved_at,
    published_at = EXCLUDED.published_at,
    attributes = EXCLUDED.attributes,
    contact_snapshot = EXCLUDED.contact_snapshot,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();

WITH real_places (
  id,
  name,
  slug,
  description,
  city,
  address,
  lat,
  lng,
  cover_image,
  source_title,
  source_url,
  source_license,
  media_title,
  media_source_url,
  media_author,
  media_license_url,
  media_license_name
) AS (
  VALUES
    (
      '58000000-0000-0000-0000-000000000801'::uuid,
      'Pasar Beringharjo',
      'pasar-beringharjo-yogyakarta',
      'Pasar tradisional nyata di Yogyakarta; referensi lokasi publik, bukan toko individual.',
      'Yogyakarta',
      'Jl. Marga Mulya No.16, Yogyakarta',
      -7.798925,
      110.365616,
      'https://commons.wikimedia.org/wiki/Special:FilePath/Jalan-jalan_ke_Pasar_Beringharjo-12.jpg?width=1200',
      'Cagar Budaya - Pasar Beringharjo',
      'https://budaya.data.kemdikbud.go.id/cagarbudaya/objek/KB001567',
      'Public cultural heritage data',
      'Jalan-jalan ke Pasar Beringharjo-12.jpg',
      'https://commons.wikimedia.org/wiki/File:Jalan-jalan_ke_Pasar_Beringharjo-12.jpg',
      'Indonesiagood',
      'https://creativecommons.org/licenses/by/3.0/',
      'CC BY 3.0'
    ),
    (
      '58000000-0000-0000-0000-000000000802'::uuid,
      'Pasar Tanah Abang',
      'pasar-tanah-abang-jakarta',
      'Kawasan pasar tekstil nyata di Jakarta Pusat; referensi publik tanpa kontak privat.',
      'Jakarta Pusat',
      'Tanah Abang, Jakarta Pusat',
      -6.2028,
      106.8196,
      'https://commons.wikimedia.org/wiki/Special:FilePath/Flood_Canal_Bisecting_Pasar_Tanah_Abang.jpg?width=1200',
      'Wikimedia Commons Category: Tanah Abang',
      'https://commons.wikimedia.org/wiki/Category:Tanah_Abang',
      'Free Wikimedia text/media subject page',
      'Flood Canal Bisecting Pasar Tanah Abang.jpg',
      'https://commons.wikimedia.org/wiki/File:Flood_Canal_Bisecting_Pasar_Tanah_Abang.jpg',
      'christian r',
      'https://creativecommons.org/licenses/by-sa/2.0/',
      'CC BY-SA 2.0'
    ),
    (
      '58000000-0000-0000-0000-000000000803'::uuid,
      'Pasar Klewer',
      'pasar-klewer-surakarta',
      'Pasar tekstil dan batik nyata di Surakarta; referensi OSM/Wikidata.',
      'Surakarta',
      'Pasar Klewer, Surakarta, Jawa Tengah',
      -7.57547,
      110.82653,
      'https://commons.wikimedia.org/wiki/Special:FilePath/Pasar_Klewer.jpg?width=1200',
      'Indonesia Travel - Pasar Klewer',
      'https://www.indonesia.travel/id/id/destination/java/central-java/klewer-market',
      'Public tourism reference',
      'Pasar Klewer.jpg',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer.jpg',
      'CoolFrame Photography / WikiSanktGerard',
      'https://commons.wikimedia.org/wiki/File:Pasar_Klewer.jpg',
      'Public domain'
    ),
    (
      '58000000-0000-0000-0000-000000000804'::uuid,
      'Kampung Batik Laweyan',
      'kampung-batik-laweyan-surakarta',
      'Kawasan batik nyata di Surakarta; referensi ekosistem usaha kreatif.',
      'Surakarta',
      'Laweyan, Surakarta, Jawa Tengah',
      -7.56083,
      110.79306,
      'https://commons.wikimedia.org/wiki/Special:FilePath/Becak_Kampung_Batik_Laweyan.jpg?width=1200',
      'Kampoeng Batik Laweyan',
      'https://kampoengbatiklaweyan.org/',
      'Public website reference',
      'Becak Kampung Batik Laweyan.jpg',
      'https://commons.wikimedia.org/wiki/File:Becak_Kampung_Batik_Laweyan.jpg',
      'Herusutimbul',
      'https://creativecommons.org/licenses/by-sa/4.0/',
      'CC BY-SA 4.0'
    ),
    (
      '58000000-0000-0000-0000-000000000805'::uuid,
      'Pasar Terapung Lok Baintan',
      'pasar-terapung-lok-baintan-banjar',
      'Pasar terapung nyata di Kabupaten Banjar; referensi publik tanpa kontak privat.',
      'Banjar',
      'Sungai Pinang, Kabupaten Banjar, Kalimantan Selatan',
      -3.296355,
      114.691953,
      'https://commons.wikimedia.org/wiki/Special:FilePath/Lokbaintan.jpg?width=1200',
      'Wikimedia Commons Category: Lok Baintan Floating Market',
      'https://commons.wikimedia.org/wiki/Category:Lok_Baintan_Floating_Market',
      'Free Wikimedia text/media subject page',
      'Lokbaintan.jpg',
      'https://commons.wikimedia.org/wiki/File:Lokbaintan.jpg',
      'Rifki Muslim',
      'https://creativecommons.org/licenses/by-sa/4.0/',
      'CC BY-SA 4.0'
    )
)
INSERT INTO umkm_stores (
  id,
  owner_user_id,
  name,
  slug,
  description,
  city,
  address,
  lat,
  lng,
  phone,
  is_active,
  online_order_enabled,
  offline_order_enabled,
  metadata
)
SELECT
  id,
  '00000000-0000-0000-0000-000000000801',
  name,
  slug,
  description,
  city,
  address,
  lat,
  lng,
  NULL,
  TRUE,
  FALSE,
  FALSE,
  jsonb_strip_nulls(
    jsonb_build_object(
      'seed_pack', 'real_indonesia_open_data_20260723',
      'record_kind', 'real_place_reference',
      'is_transactional', false,
      'contact_policy', 'no_private_contact_seeded',
      'open_hours', 'Lihat sumber resmi/lokal terbaru',
      'highlight', 'Referensi tempat nyata dari sumber publik',
      'cover_image_url', cover_image,
      'image_url', cover_image,
      'gallery_images', jsonb_build_array(cover_image),
      'source', jsonb_build_object(
        'title', source_title,
        'url', source_url,
        'license', source_license,
        'access', 'public'
      ),
      'image_credit', jsonb_build_object(
        'provider', 'Wikimedia Commons',
        'title', media_title,
        'source_url', media_source_url,
        'author', media_author,
        'license_url', media_license_url,
        'license', media_license_name,
        'note', 'Free/public media reference. Keep attribution when reusing.'
      ),
      'trust_note', 'Real place reference only. Ordering and phone contact are intentionally disabled.'
    )
  )
FROM real_places
ON CONFLICT (id) DO UPDATE
SET owner_user_id = EXCLUDED.owner_user_id,
    name = EXCLUDED.name,
    slug = EXCLUDED.slug,
    description = EXCLUDED.description,
    city = EXCLUDED.city,
    address = EXCLUDED.address,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    phone = EXCLUDED.phone,
    is_active = EXCLUDED.is_active,
    online_order_enabled = EXCLUDED.online_order_enabled,
    offline_order_enabled = EXCLUDED.offline_order_enabled,
    metadata = EXCLUDED.metadata,
    updated_at = NOW();
