import type { LajukanAvatarPreset, LajukanAvatarSpec } from './types';

export const DEFAULT_LAJUKAN_AVATAR: LajukanAvatarSpec = {
  version: 2,
  body: 'classic',
  skin: 'sawo',
  hair: 'wave',
  hairColor: 'espresso',
  headwear: 'none',
  eyewear: 'none',
  faceAccessory: 'none',
  accessory: 'none',
  outfit: 'tee',
  outfitColor: 'emerald',
  background: 'mint',
  effect: 'none',
  wing: 'none',
  aura: 'none',
  backItem: 'none',
  handItem: 'none',
  mood: 'smile',
  pose: 'idle',
  motion: 'full',
};

export const LAJUKAN_AVATAR_PRESETS: ReadonlyArray<LajukanAvatarPreset> = [
  {
    key: 'default',
    labelId: 'Default Polos',
    labelEn: 'Clean Default',
    captionId: 'Awal netral, siap dicustom.',
    captionEn: 'Neutral starter, ready to customize.',
    rarity: 'Basic',
    spec: DEFAULT_LAJUKAN_AVATAR,
  },
  {
    key: 'umkm-owner',
    labelId: 'Owner UMKM',
    labelEn: 'SME Owner',
    captionId: 'Rapi, percaya diri, siap jualan.',
    captionEn: 'Neat, confident, ready to sell.',
    rarity: 'Rare',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      outfit: 'jacket',
      outfitColor: 'slate',
      aura: 'halo',
      handItem: 'phone',
      mood: 'determined',
      background: 'sky',
      effect: 'halo',
    },
  },
  {
    key: 'food-merchant',
    labelId: 'Food Merchant',
    labelEn: 'Food Merchant',
    captionId: 'Apron, chef hat, vibes kuliner.',
    captionEn: 'Apron, chef hat, culinary energy.',
    rarity: 'Rare',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      headwear: 'chef',
      accessory: 'none',
      outfit: 'apron',
      outfitColor: 'emerald',
      aura: 'spark',
      handItem: 'coffee',
      background: 'sunset',
    },
  },
  {
    key: 'marketplace-seller',
    labelId: 'Marketplace Seller',
    labelEn: 'Marketplace Seller',
    captionId: 'Paket siap kirim, sayap crystal.',
    captionEn: 'Package ready, crystal wings.',
    rarity: 'Epic',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      body: 'small',
      hair: 'crop',
      wing: 'crystal',
      aura: 'energy',
      backItem: 'shield',
      handItem: 'package',
      outfitColor: 'sky',
      background: 'neon',
      effect: 'wings',
    },
  },
  {
    key: 'freelancer',
    labelId: 'Freelancer',
    labelEn: 'Freelancer',
    captionId: 'Hoodie, kacamata, siap presentasi.',
    captionEn: 'Hoodie, glasses, presentation-ready.',
    rarity: 'Rare',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      hair: 'curly',
      eyewear: 'glasses',
      accessory: 'glasses',
      outfit: 'hoodie',
      outfitColor: 'violet',
      handItem: 'phone',
      mood: 'cool',
      background: 'slate',
    },
  },
  {
    key: 'service-pro',
    labelId: 'Service Pro',
    labelEn: 'Service Pro',
    captionId: 'Tool siap, tampilan teknisi pro.',
    captionEn: 'Tools ready, pro technician look.',
    rarity: 'Epic',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      body: 'sturdy',
      headwear: 'cap',
      accessory: 'cap',
      outfit: 'jacket',
      outfitColor: 'amber',
      aura: 'orbit',
      handItem: 'wrench',
      mood: 'determined',
      background: 'mint',
    },
  },
  {
    key: 'driver-courier',
    labelId: 'Driver/Courier',
    labelEn: 'Driver/Courier',
    captionId: 'Helm, jacket, jetpack arcade.',
    captionEn: 'Helmet, jacket, arcade jetpack.',
    rarity: 'Legend',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      headwear: 'helmet',
      outfit: 'driver',
      outfitColor: 'amber',
      backItem: 'jetpack',
      aura: 'energy',
      handItem: 'package',
      pose: 'ready',
      background: 'sky',
      effect: 'trail',
    },
  },
  {
    key: 'property',
    labelId: 'Property',
    labelEn: 'Property',
    captionId: 'Batik elegan dan shield trusted.',
    captionEn: 'Elegant batik with trusted shield.',
    rarity: 'Epic',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      hair: 'long',
      outfit: 'batik',
      outfitColor: 'rose',
      backItem: 'shield',
      aura: 'halo',
      handItem: 'phone',
      background: 'rose',
      effect: 'halo',
    },
  },
  {
    key: 'tool-rental',
    labelId: 'Tool Rental',
    labelEn: 'Tool Rental',
    captionId: 'Mecha wing, wrench, utility mode.',
    captionEn: 'Mecha wing, wrench, utility mode.',
    rarity: 'Legend',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      body: 'sturdy',
      headwear: 'cap',
      accessory: 'cap',
      outfit: 'jacket',
      outfitColor: 'slate',
      wing: 'mechanical',
      aura: 'orbit',
      handItem: 'wrench',
      mood: 'cool',
      background: 'neon',
      effect: 'wings',
    },
  },
  {
    key: 'reels-creator',
    labelId: 'Reels Creator',
    labelEn: 'Reels Creator',
    captionId: 'Kamera, spark, gaya kreator.',
    captionEn: 'Camera, spark, creator look.',
    rarity: 'Legend',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      hair: 'bun',
      hairColor: 'auburn',
      eyewear: 'shades',
      outfit: 'hoodie',
      outfitColor: 'rose',
      wing: 'flame',
      aura: 'rainbow',
      handItem: 'camera',
      mood: 'wink',
      background: 'neon',
      effect: 'trail',
    },
  },
  {
    key: 'royal-supplier',
    labelId: 'Royal Supplier',
    labelEn: 'Royal Supplier',
    captionId: 'Banner, wings royal, siap pasok besar.',
    captionEn: 'Banner, royal wings, ready for bigger supply.',
    rarity: 'Legend',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      body: 'athletic',
      skin: 'olive',
      hair: 'sidepart',
      hairColor: 'hazel',
      headwear: 'fedora',
      outfit: 'vest',
      outfitColor: 'gold',
      wing: 'royal',
      aura: 'coins',
      backItem: 'banner',
      handItem: 'tablet',
      mood: 'proud',
      pose: 'hero',
      background: 'warehouse',
      effect: 'wings',
    },
  },
  {
    key: 'chef-pro',
    labelId: 'Chef Pro',
    labelEn: 'Chef Pro',
    captionId: 'Chef coat, spatula, aura market.',
    captionEn: 'Chef coat, spatula, market aura.',
    rarity: 'Epic',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      skin: 'rosewarm',
      headwear: 'chef',
      outfit: 'chefcoat',
      outfitColor: 'cream',
      aura: 'flame',
      handItem: 'spatula',
      mood: 'happy',
      pose: 'hold',
      background: 'market',
      effect: 'trail',
    },
  },
  {
    key: 'live-commerce-host',
    labelId: 'Live Commerce Host',
    labelEn: 'Live Commerce Host',
    captionId: 'Mic, prism wing, siap jualan live.',
    captionEn: 'Mic, prism wings, ready to go live.',
    rarity: 'Legend',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      body: 'tall',
      skin: 'kuning',
      hair: 'ponytail',
      hairColor: 'copper',
      eyewear: 'round',
      outfit: 'kebaya',
      outfitColor: 'rose',
      wing: 'prism',
      aura: 'stars',
      handItem: 'microphone',
      mood: 'happy',
      pose: 'wave',
      background: 'studio',
      effect: 'wings',
    },
  },
  {
    key: 'workshop-mechanic',
    labelId: 'Workshop Mechanic',
    labelEn: 'Workshop Mechanic',
    captionId: 'Overall, toolbox, wing techno.',
    captionEn: 'Overalls, toolbox, techno wings.',
    rarity: 'Legend',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      body: 'sturdy',
      skin: 'tan',
      hair: 'fade',
      headwear: 'helmet',
      outfit: 'overalls',
      outfitColor: 'navy',
      wing: 'techno',
      aura: 'matrix',
      backItem: 'toolbox',
      handItem: 'wrench',
      mood: 'serious',
      pose: 'ready',
      background: 'workshop',
      effect: 'wings',
    },
  },
  {
    key: 'fashion-merchant',
    labelId: 'Fashion Merchant',
    labelEn: 'Fashion Merchant',
    captionId: 'Butterfly wings, tas jualan, rapi.',
    captionEn: 'Butterfly wings, shopping bag, stylish.',
    rarity: 'Epic',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      body: 'rounded',
      skin: 'mahogany',
      hair: 'braids',
      hairColor: 'midnight',
      headwear: 'turban',
      outfit: 'kebaya',
      outfitColor: 'teal',
      wing: 'butterfly',
      aura: 'mist',
      handItem: 'shoppingBag',
      mood: 'smile',
      background: 'market',
      effect: 'wings',
    },
  },
  {
    key: 'export-courier',
    labelId: 'Export Courier',
    labelEn: 'Export Courier',
    captionId: 'Phoenix wing, paket ekspor, rute cepat.',
    captionEn: 'Phoenix wings, export package, fast route.',
    rarity: 'Legend',
    spec: {
      ...DEFAULT_LAJUKAN_AVATAR,
      body: 'athletic',
      skin: 'sawo',
      hair: 'spiky',
      hairColor: 'black',
      headwear: 'visor',
      outfit: 'uniform',
      outfitColor: 'sky',
      wing: 'phoenix',
      aura: 'energy',
      backItem: 'jetpack',
      handItem: 'package',
      mood: 'determined',
      pose: 'hold',
      background: 'map',
      effect: 'wings',
    },
  },
];
