export const IMAGE_UPLOAD_RAW_MAX_MB = 20;
export const IMAGE_UPLOAD_RAW_MAX_BYTES = IMAGE_UPLOAD_RAW_MAX_MB * 1024 * 1024;

export const IMAGE_UPLOAD_TARGET_MB = 5;
export const IMAGE_UPLOAD_TARGET_BYTES = IMAGE_UPLOAD_TARGET_MB * 1024 * 1024;

export const IMAGE_UPLOAD_MIN_BYTES_TO_COMPRESS = 256 * 1024;
export const IMAGE_UPLOAD_MAX_DIMENSION = 1280;
export const IMAGE_UPLOAD_QUALITY = 0.74;
export const IMAGE_UPLOAD_MIN_QUALITY = 0.62;

export const MEDIA_UPLOAD_RAW_MAX_MB = 120;
export const MEDIA_UPLOAD_RAW_MAX_BYTES = MEDIA_UPLOAD_RAW_MAX_MB * 1024 * 1024;

export const VOICE_NOTE_UPLOAD_MAX_MB = 16;
export const VOICE_NOTE_UPLOAD_MAX_BYTES =
  VOICE_NOTE_UPLOAD_MAX_MB * 1024 * 1024;

export const DOCUMENT_UPLOAD_MAX_MB = 80;
export const DOCUMENT_UPLOAD_MAX_BYTES = DOCUMENT_UPLOAD_MAX_MB * 1024 * 1024;
