export const Z_INDEX = {
  default: 1,
  contentRaised: 10,
  sidebar: 30,
  stickyControls: 40,
  bottomNavbar: 50,
  header: 90,
  navPopover: 160,
  drawer: 170,
  modal: 200,
  loading: 998,
  bgBlur: 190,
  preview: 1000,
  thumnailPreview: 1000,
  notFound: 999999,
  offline: 999,
  overflay: 998,
};

export const Z_INDEX_CLASS = {
  contentRaised: 'ui-layer-content-raised',
  sidebar: 'ui-layer-sidebar',
  stickyControls: 'ui-layer-sticky',
  bottomNavbar: 'ui-layer-bottom-nav',
  mobileTopbar: 'ui-layer-mobile-topbar',
  header: 'ui-layer-header',
  localTopbar: 'ui-layer-local-topbar',
  navPopover: 'ui-layer-popover',
  drawer: 'ui-layer-drawer',
  modalBackdrop: 'ui-layer-modal-backdrop',
  modal: 'ui-layer-modal',
  loading: 'ui-layer-loading',
  offline: 'ui-layer-offline',
  preview: 'ui-layer-preview',
  notFound: 'ui-layer-not-found',
} as const;
