import type {
  BusinessRecord,
  PermissionId,
  PortalRole,
  RoleSummary,
  SecurityEvent,
  TeamMember,
} from '@/lib/portal-types';
import {
  buildBusinessGoogleMapsUrl,
  buildPublicStorefrontUrl,
} from '@/lib/portal-links';

export const permissionMap: Record<PortalRole, PermissionId[]> = {
  owner: [
    'viewInfo',
    'manageInfo',
    'viewProducts',
    'manageProducts',
    'viewOrders',
    'manageOrders',
    'viewOperations',
    'manageOperations',
    'viewTeam',
    'inviteMembers',
    'manageRoles',
    'viewBuyerPage',
    'openBusiness',
    'manageSecurity',
  ],
  manager: [
    'viewInfo',
    'manageInfo',
    'viewProducts',
    'manageProducts',
    'viewOrders',
    'manageOrders',
    'viewOperations',
    'manageOperations',
    'viewTeam',
    'inviteMembers',
    'viewBuyerPage',
    'openBusiness',
  ],
  cashier: [
    'viewProducts',
    'viewOrders',
    'manageOrders',
    'viewOperations',
    'manageOperations',
    'viewBuyerPage',
  ],
  viewer: ['viewInfo', 'viewProducts', 'viewOrders', 'viewOperations', 'viewBuyerPage'],
};

export const roleSummaryMap: Record<PortalRole, RoleSummary> = {
  owner: {
    label: 'Owner',
    shortLabel: 'Pemilik penuh',
    description:
      'Pegang keputusan sensitif usaha: info utama, produk, operasional, tim, dan pengamanan akun usaha.',
    can: [
      'Ubah info usaha',
      'Tambah atau ubah produk',
      'Buka dan tutup usaha',
      'Undang anggota serta atur jabatan',
      'Aktifkan PIN usaha dan audit log',
    ],
    cannot: [],
  },
  manager: {
    label: 'Manager',
    shortLabel: 'Pengelola harian',
    description:
      'Fokus pada ritme usaha harian: produk, pesanan, operasional, dan koordinasi tim tanpa akses kepemilikan penuh.',
    can: [
      'Lihat dan proses pesanan',
      'Atur produk dan stok',
      'Atur operasional harian',
      'Lihat tim dan kirim undangan',
    ],
    cannot: ['Pindah kepemilikan usaha', 'Atur akses sensitif'],
  },
  cashier: {
    label: 'Kasir',
    shortLabel: 'Transaksi & lapangan',
    description:
      'Cocok untuk anggota yang memegang pesanan, meja, pembayaran, dan ritme operasional di lapangan.',
    can: ['Lihat pesanan', 'Proses pesanan', 'Kelola meja dan QR', 'Cek reservasi'],
    cannot: ['Ubah info usaha', 'Atur tim', 'Atur pengamanan sensitif'],
  },
  viewer: {
    label: 'Viewer',
    shortLabel: 'Akses baca saja',
    description:
      'Cocok untuk partner, auditor, atau pihak pemantau yang hanya perlu melihat ringkasan tanpa mengubah data.',
    can: ['Lihat ringkasan usaha', 'Pantau produk dan status order'],
    cannot: ['Tambah produk', 'Atur operasional', 'Undang anggota'],
  },
};

function buildSecurityEvents(scope: string): SecurityEvent[] {
  return [
    {
      id: `${scope}-1`,
      title: 'Login dari perangkat baru',
      description: 'Galaxy A55 - Jakarta Timur. Sistem meminta verifikasi OTP sebelum sesi aktif.',
      time: 'Hari ini, 08.14',
    },
    {
      id: `${scope}-2`,
      title: 'PIN usaha diubah',
      description: 'PIN usaha terakhir diperbarui oleh owner utama.',
      time: 'Kemarin, 21.03',
    },
    {
      id: `${scope}-3`,
      title: 'Undangan jabatan dikirim',
      description: 'Satu undangan baru dikirim ke anggota tim operasional.',
      time: 'Kemarin, 16.20',
    },
  ];
}

const warungTeam: TeamMember[] = [
  {
    id: 'member-nadia',
    name: 'Nadia Putri',
    phone: '0812-1111-2222',
    role: 'owner',
    status: 'active',
    area: 'Owner utama',
    lastSeen: 'Baru saja aktif',
  },
];

const kopiTeam: TeamMember[] = [
  {
    id: 'member-rian',
    name: 'Rian Saputra',
    phone: '0813-1111-3344',
    role: 'manager',
    status: 'active',
    area: 'Manager shift pagi',
    lastSeen: '5 menit lalu',
  },
  {
    id: 'member-sari',
    name: 'Sari Aprilia',
    phone: '0812-9988-7766',
    role: 'cashier',
    status: 'active',
    area: 'Kasir utama',
    lastSeen: '12 menit lalu',
  },
  {
    id: 'member-danu',
    name: 'Danu Prasetyo',
    phone: '0813-4444-7788',
    role: 'cashier',
    status: 'active',
    area: 'Kasir closing',
    lastSeen: '30 menit lalu',
  },
  {
    id: 'member-fitri',
    name: 'Fitri Aulia',
    phone: '0819-6644-2288',
    role: 'viewer',
    status: 'active',
    area: 'Laporan dan pemantauan',
    lastSeen: '1 jam lalu',
  },
];

export const businesses: BusinessRecord[] = [
  {
    id: 'warung-barokah',
    slug: 'warung-barokah',
    name: 'Warung Barokah',
    currentRole: 'owner',
    city: 'Depok',
    address: 'Jl. Tole Iskandar No. 18, Depok',
    latitude: -6.402209,
    longitude: 106.821862,
    locationQuery: 'Warung Barokah, Jl. Tole Iskandar No. 18, Depok',
    googleMapsUrl: buildBusinessGoogleMapsUrl({
      name: 'Warung Barokah',
      address: 'Jl. Tole Iskandar No. 18, Depok',
      city: 'Depok',
      latitude: -6.402209,
      longitude: 106.821862,
    }),
    category: 'Makanan & minuman',
    phone: '0812-1111-2222',
    description:
      'Warung sarapan, jajanan, dan titip jual warga sekitar dengan ritme stok yang perlu gampang dicek oleh owner maupun kasir.',
    schedule: '06.00 - 21.00',
    infoComplete: true,
    productsCount: 4,
    isOpen: true,
    buyerPageReady: true,
    activeOrders: 2,
    reservationsCount: 0,
    teamMembers: warungTeam,
    invites: [
      {
        id: 'invite-1',
        name: 'Budi Santoso',
        phone: '0812-7777-8899',
        role: 'cashier',
        status: 'pending',
        sentAt: 'Hari ini, 09.10',
      },
      {
        id: 'invite-2',
        name: 'Dewi Lestari',
        phone: '0813-2323-4545',
        role: 'manager',
        status: 'pending',
        sentAt: 'Kemarin, 18.40',
      },
    ],
    products: [
      {
        id: 'prod-warung-1',
        name: 'Nasi Uduk Pagi',
        priceLabel: 'Rp12.000',
        stockLabel: 'Sisa 9 bungkus',
        category: 'Sarapan',
        status: 'live',
        sourceType: 'owned',
        ownerLabel: 'Dapur warung',
        stockCount: 9,
        stockUnit: 'bungkus',
        minStockAlert: 6,
        stockMode: 'manual',
        stockHealth: 'aman',
        stockUpdatedAt: 'Hari ini, 06.10',
        notes: 'Hitung ulang sebelum jam 10.00.',
      },
      {
        id: 'prod-warung-2',
        name: 'Keripik Pisang Bu Rini',
        priceLabel: 'Rp8.000',
        stockLabel: 'Sisa 4 pcs',
        category: 'Titipan snack',
        status: 'live',
        sourceType: 'consignment',
        ownerLabel: 'Bu Rini Snack',
        stockCount: 4,
        stockUnit: 'pcs',
        minStockAlert: 5,
        stockMode: 'estimated',
        stockHealth: 'perlu-cocokkan',
        stockUpdatedAt: 'Kemarin, 17.40',
        consignmentTerms: 'Bagi hasil 80/20, setor tiap Jumat.',
        notes: 'Sering habis saat jam pulang sekolah.',
      },
      {
        id: 'prod-warung-3',
        name: 'Telur Gulung Paket 3',
        priceLabel: 'Rp10.000',
        stockLabel: 'Sisa 3 tusuk',
        category: 'Jajanan',
        status: 'live',
        sourceType: 'owned',
        ownerLabel: 'Dapur warung',
        stockCount: 3,
        stockUnit: 'tusuk',
        minStockAlert: 4,
        stockMode: 'manual',
        stockHealth: 'tipis',
        stockUpdatedAt: 'Hari ini, 14.05',
      },
      {
        id: 'prod-warung-4',
        name: 'Brownies Kukus Lala',
        priceLabel: 'Rp15.000',
        stockLabel: 'Belum dicocokkan',
        category: 'Titipan kue',
        status: 'live',
        sourceType: 'consignment',
        ownerLabel: 'Lala Bakery Rumahan',
        stockCount: null,
        stockUnit: 'box',
        minStockAlert: 2,
        stockMode: 'estimated',
        stockHealth: 'perlu-cocokkan',
        stockUpdatedAt: '2 hari lalu',
        consignmentTerms: 'Setor laku per Senin dan Kamis.',
        notes: 'Penitip kirim ulang bila ada sisa di bawah 2 box.',
      },
    ],
    orders: [
      {
        id: 'order-warung-1',
        buyer: 'Andi',
        itemSummary: '2 Nasi Uduk Pagi + 1 Keripik Pisang',
        amountLabel: 'Rp32.000',
        status: 'baru',
        channel: 'WhatsApp tetangga',
      },
      {
        id: 'order-warung-2',
        buyer: 'Salsa',
        itemSummary: '3 Brownies Kukus Lala',
        amountLabel: 'Rp45.000',
        status: 'diproses',
        channel: 'Titip sore sekolah',
      },
    ],
    reservations: [],
    permissions: permissionMap.owner,
    publicUrl: buildPublicStorefrontUrl('warung-barokah'),
    securityEvents: buildSecurityEvents('warung'),
  },
  {
    id: 'kopi-santai',
    slug: 'kopi-santai',
    name: 'Kopi Santai',
    currentRole: 'manager',
    city: 'Bandung',
    address: 'Jl. Ciumbuleuit No. 44, Bandung',
    latitude: -6.875493,
    longitude: 107.60458,
    locationQuery: 'Kopi Santai, Jl. Ciumbuleuit No. 44, Bandung',
    googleMapsUrl: buildBusinessGoogleMapsUrl({
      name: 'Kopi Santai',
      address: 'Jl. Ciumbuleuit No. 44, Bandung',
      city: 'Bandung',
      latitude: -6.875493,
      longitude: 107.60458,
    }),
    category: 'Cafe & kopi',
    phone: '0813-1111-3344',
    description:
      'Cafe neighborhood dengan fokus dine-in, reservasi kecil, dan pengiriman cepat lewat kurir partner.',
    schedule: '08.00 - 23.00',
    infoComplete: true,
    productsCount: 18,
    isOpen: true,
    buyerPageReady: true,
    activeOrders: 7,
    reservationsCount: 3,
    teamMembers: kopiTeam,
    invites: [
      {
        id: 'invite-3',
        name: 'Yoga Pradana',
        phone: '0812-7766-1100',
        role: 'cashier',
        status: 'accepted',
        sentAt: '2 hari lalu',
      },
      {
        id: 'invite-4',
        name: 'Nina Maharani',
        phone: '0812-6633-1100',
        role: 'viewer',
        status: 'pending',
        sentAt: 'Hari ini, 10.25',
      },
    ],
    products: [
      {
        id: 'prod-1',
        name: 'Es Kopi Susu Santai',
        priceLabel: 'Rp24.000',
        stockLabel: 'Tersedia',
        category: 'Minuman dingin',
        status: 'live',
      },
      {
        id: 'prod-2',
        name: 'Kopi Tubruk Aren',
        priceLabel: 'Rp20.000',
        stockLabel: 'Tersedia',
        category: 'Minuman panas',
        status: 'live',
      },
      {
        id: 'prod-3',
        name: 'Croissant Butter',
        priceLabel: 'Rp28.000',
        stockLabel: 'Stok tipis',
        category: 'Pastry',
        status: 'live',
      },
    ],
    orders: [
      {
        id: 'order-101',
        buyer: 'Maya',
        itemSummary: '2 Es Kopi Susu Santai',
        amountLabel: 'Rp48.000',
        status: 'baru',
        channel: 'GoSend instant',
      },
      {
        id: 'order-102',
        buyer: 'Roni',
        itemSummary: '1 Latte + 1 Croissant',
        amountLabel: 'Rp54.000',
        status: 'diproses',
        channel: 'Dine-in meja 04',
      },
      {
        id: 'order-103',
        buyer: 'Nadia',
        itemSummary: '3 Americano',
        amountLabel: 'Rp63.000',
        status: 'siap kirim',
        channel: 'Pickup',
      },
    ],
    reservations: [
      {
        id: 'book-1',
        guest: 'Rizky dan tim',
        schedule: 'Hari ini, 19.00',
        pax: '5 orang',
        status: 'terkonfirmasi',
      },
      {
        id: 'book-2',
        guest: 'Alya',
        schedule: 'Hari ini, 20.30',
        pax: '2 orang',
        status: 'menunggu',
      },
    ],
    permissions: permissionMap.manager,
    publicUrl: buildPublicStorefrontUrl('kopi-santai'),
    securityEvents: buildSecurityEvents('kopi'),
  },
  {
    id: 'gudeg-kilat',
    slug: 'gudeg-kilat',
    name: 'Gudeg Kilat',
    currentRole: 'cashier',
    city: 'Yogyakarta',
    address: 'Jl. Gejayan No. 12, Sleman',
    latitude: -7.774214,
    longitude: 110.380303,
    locationQuery: 'Gudeg Kilat, Jl. Gejayan No. 12, Sleman, Yogyakarta',
    googleMapsUrl: buildBusinessGoogleMapsUrl({
      name: 'Gudeg Kilat',
      address: 'Jl. Gejayan No. 12, Sleman',
      city: 'Yogyakarta',
      latitude: -7.774214,
      longitude: 110.380303,
    }),
    category: 'Makanan cepat saji',
    phone: '0813-5544-2200',
    description:
      'Outlet kecil dengan fokus order cepat, pickup, dan meja terbatas. Ritme kerjanya sangat operasional.',
    schedule: '07.00 - 22.00',
    infoComplete: true,
    productsCount: 9,
    isOpen: true,
    buyerPageReady: true,
    activeOrders: 12,
    reservationsCount: 2,
    teamMembers: [
      {
        id: 'member-elsa',
        name: 'Elsa Puspita',
        phone: '0812-3311-7788',
        role: 'cashier',
        status: 'active',
        area: 'Kasir dan meja',
        lastSeen: 'Sedang aktif',
      },
      {
        id: 'member-adit',
        name: 'Adit Wibowo',
        phone: '0813-8811-0099',
        role: 'manager',
        status: 'active',
        area: 'Manager outlet',
        lastSeen: '20 menit lalu',
      },
    ],
    invites: [],
    products: [
      {
        id: 'prod-8',
        name: 'Gudeg Komplit',
        priceLabel: 'Rp31.000',
        stockLabel: 'Tersedia',
        category: 'Menu utama',
        status: 'live',
      },
      {
        id: 'prod-9',
        name: 'Teh Panas',
        priceLabel: 'Rp6.000',
        stockLabel: 'Tersedia',
        category: 'Minuman',
        status: 'live',
      },
    ],
    orders: [
      {
        id: 'order-201',
        buyer: 'Anton',
        itemSummary: '2 Gudeg Komplit',
        amountLabel: 'Rp62.000',
        status: 'baru',
        channel: 'Pickup',
      },
      {
        id: 'order-202',
        buyer: 'Wulan',
        itemSummary: '1 Gudeg Komplit + 2 Teh Panas',
        amountLabel: 'Rp43.000',
        status: 'diproses',
        channel: 'Meja 02',
      },
    ],
    reservations: [
      {
        id: 'book-8',
        guest: 'Komunitas Pagi',
        schedule: 'Hari ini, 11.30',
        pax: '6 orang',
        status: 'menunggu',
      },
    ],
    permissions: permissionMap.cashier,
    publicUrl: buildPublicStorefrontUrl('gudeg-kilat'),
    securityEvents: buildSecurityEvents('gudeg'),
  },
  {
    id: 'laundry-express',
    slug: 'laundry-express',
    name: 'Laundry Express',
    currentRole: 'viewer',
    city: 'Bekasi',
    address: 'Jl. Ahmad Yani No. 90, Bekasi',
    latitude: -6.241769,
    longitude: 106.998795,
    locationQuery: 'Laundry Express, Jl. Ahmad Yani No. 90, Bekasi',
    googleMapsUrl: buildBusinessGoogleMapsUrl({
      name: 'Laundry Express',
      address: 'Jl. Ahmad Yani No. 90, Bekasi',
      city: 'Bekasi',
      latitude: -6.241769,
      longitude: 106.998795,
    }),
    category: 'Jasa laundry',
    phone: '0812-4422-6633',
    description:
      'Usaha jasa laundry kiloan dengan fokus monitoring performa, status order, dan jam operasional.',
    schedule: '09.00 - 20.00',
    infoComplete: true,
    productsCount: 5,
    isOpen: true,
    buyerPageReady: true,
    activeOrders: 2,
    reservationsCount: 0,
    teamMembers: [
      {
        id: 'member-arya',
        name: 'Arya Putra',
        phone: '0812-8899-6655',
        role: 'viewer',
        status: 'active',
        area: 'Pemantau laporan',
        lastSeen: '1 jam lalu',
      },
    ],
    invites: [
      {
        id: 'invite-99',
        name: 'Siti Rahma',
        phone: '0813-9898-2211',
        role: 'viewer',
        status: 'declined',
        sentAt: '3 hari lalu',
      },
    ],
    products: [
      {
        id: 'prod-22',
        name: 'Laundry Kiloan',
        priceLabel: 'Rp8.000/kg',
        stockLabel: 'Aktif',
        category: 'Jasa',
        status: 'live',
      },
      {
        id: 'prod-23',
        name: 'Cuci Express 6 Jam',
        priceLabel: 'Rp18.000/kg',
        stockLabel: 'Aktif',
        category: 'Jasa premium',
        status: 'live',
      },
    ],
    orders: [
      {
        id: 'order-301',
        buyer: 'Khalid',
        itemSummary: 'Laundry Kiloan 4 kg',
        amountLabel: 'Rp32.000',
        status: 'baru',
        channel: 'Antar-jemput',
      },
    ],
    reservations: [],
    permissions: permissionMap.viewer,
    publicUrl: buildPublicStorefrontUrl('laundry-express'),
    securityEvents: buildSecurityEvents('laundry'),
  },
];

export const guestHighlights = [
  'Buat usaha, tambah produk, dan atur tim dari satu domain yang khusus untuk mode bisnis.',
  'Pakai jabatan dan akses per usaha, jadi akun yang sama tetap bisa pegang banyak usaha berbeda.',
  'Aksi sensitif seperti undang anggota, ubah jabatan, dan buka usaha nanti bisa dipaksa pakai PIN usaha.',
];

export function getBusinessById(id: string) {
  return businesses.find(business => business.id === id) ?? null;
}

export function getDefaultBusinessId() {
  return businesses[0]?.id ?? null;
}
