import type {
  PermissionId,
  PortalRole,
  RoleSummary,
} from '@/lib/portal-types';

export const permissionMap: Record<PortalRole, PermissionId[]> = {
  owner: [
    'viewInfo',
    'manageInfo',
    'viewProducts',
    'manageProducts',
    'viewCosting',
    'manageCosting',
    'viewInventory',
    'manageInventory',
    'viewOrders',
    'manageOrders',
    'viewFinance',
    'manageFinance',
    'viewChannels',
    'manageChannels',
    'viewReports',
    'viewOperations',
    'manageOperations',
    'viewTeam',
    'inviteMembers',
    'manageRoles',
    'viewBuyerPage',
    'openBusiness',
    'manageSecurity',
  ],
  manager: [
    'viewInfo',
    'manageInfo',
    'viewProducts',
    'manageProducts',
    'viewCosting',
    'manageCosting',
    'viewInventory',
    'manageInventory',
    'viewOrders',
    'manageOrders',
    'viewFinance',
    'manageFinance',
    'viewChannels',
    'manageChannels',
    'viewReports',
    'viewOperations',
    'manageOperations',
    'viewTeam',
    'inviteMembers',
    'viewBuyerPage',
    'openBusiness',
  ],
  cashier: [
    'viewProducts',
    'viewInventory',
    'viewOrders',
    'manageOrders',
    'viewOperations',
    'manageOperations',
    'viewBuyerPage',
  ],
  viewer: [
    'viewInfo',
    'viewProducts',
    'viewInventory',
    'viewOrders',
    'viewOperations',
    'viewBuyerPage',
  ],
};

export const roleSummaryMap: Record<PortalRole, RoleSummary> = {
  owner: {
    label: 'Owner',
    shortLabel: 'Pemilik penuh',
    description:
      'Melihat dan mengatur seluruh bisnis, termasuk HPP, laba, uang, kanal jual, tim, dan keamanan.',
    can: [
      'Lihat HPP, margin, laba dan saldo',
      'Atur resep, stok, harga dan kanal jual',
      'Catat uang masuk dan keluar',
      'Undang anggota serta atur jabatan',
      'Atur keamanan usaha',
    ],
    cannot: [],
  },
  manager: {
    label: 'Manager',
    shortLabel: 'Pengelola harian',
    description:
      'Mengelola penjualan, HPP, stok, kanal, dan keuangan operasional tanpa mengambil alih kepemilikan akun.',
    can: [
      'Lihat dan proses pesanan',
      'Atur produk, HPP dan stok',
      'Catat keuangan operasional',
      'Atur kanal jual dan operasional harian',
    ],
    cannot: ['Pindah kepemilikan usaha', 'Atur akses keamanan paling sensitif'],
  },
  cashier: {
    label: 'Kasir',
    shortLabel: 'Transaksi & lapangan',
    description:
      'Fokus pada pesanan dan operasional tanpa melihat biaya supplier, HPP, margin, laba, atau saldo sensitif.',
    can: [
      'Lihat produk dan stok operasional',
      'Lihat dan proses pesanan',
      'Jalankan tugas operasional',
    ],
    cannot: ['Lihat HPP dan laba', 'Lihat saldo bank', 'Ubah profil dan tim'],
  },
  viewer: {
    label: 'Viewer',
    shortLabel: 'Akses baca terbatas',
    description:
      'Melihat informasi operasional yang aman tanpa membuka data biaya dan keuangan sensitif.',
    can: ['Lihat ringkasan non-sensitif', 'Pantau produk, stok dan status order'],
    cannot: ['Lihat HPP dan laba', 'Tambah produk', 'Atur operasional', 'Undang anggota'],
  },
};
