CREATE EXTENSION IF NOT EXISTS pgcrypto;
DO $$ BEGIN CREATE TYPE order_category_type AS ENUM ('PHYSICAL_GOODS','SUPPLY_CHAIN','SERVICE_MARKETPLACE','CULINARY_INSTANT'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE order_base_status AS ENUM ('DRAFT','PENDING_PAYMENT','PAID','PROCESSING','SHIPPED','IN_SERVICE','DELIVERED','COMPLETED','CANCELLED','REJECTED','EXPIRED','REFUNDED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE order_payment_status AS ENUM ('UNPAID','PENDING','PAID','FAILED','EXPIRED','REFUND_PENDING','REFUNDED','PARTIALLY_REFUNDED'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS orders(
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),order_number TEXT NOT NULL UNIQUE,user_id UUID NOT NULL,merchant_id UUID NOT NULL,category_type order_category_type NOT NULL,base_status order_base_status NOT NULL DEFAULT 'DRAFT',payment_status order_payment_status NOT NULL DEFAULT 'UNPAID',currency CHAR(3) NOT NULL DEFAULT 'IDR',subtotal_amount NUMERIC(18,2) NOT NULL DEFAULT 0,shipping_amount NUMERIC(18,2) NOT NULL DEFAULT 0,discount_amount NUMERIC(18,2) NOT NULL DEFAULT 0,tax_amount NUMERIC(18,2) NOT NULL DEFAULT 0,total_amount NUMERIC(18,2) NOT NULL DEFAULT 0,payment_provider TEXT,payment_reference TEXT,payment_due_at TIMESTAMPTZ,accepted_at TIMESTAMPTZ,paid_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,cancelled_at TIMESTAMPTZ,expired_at TIMESTAMPTZ,refunded_at TIMESTAMPTZ,category_specific_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,idempotency_key TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),version BIGINT NOT NULL DEFAULT 1,business_id UUID,source_type TEXT);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS business_id UUID;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS source_type TEXT;\nCREATE UNIQUE INDEX IF NOT EXISTS idx_orders_idempotency_key ON orders(user_id,idempotency_key);
CREATE INDEX IF NOT EXISTS idx_orders_user_created_at ON orders(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_merchant_created_at ON orders(merchant_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(base_status,created_at DESC);
CREATE TABLE IF NOT EXISTS order_items(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id UUID,service_id UUID,sku_id UUID,item_name TEXT NOT NULL,quantity NUMERIC(18,3) NOT NULL DEFAULT 1,unit_price NUMERIC(18,2) NOT NULL DEFAULT 0,line_total NUMERIC(18,2) NOT NULL DEFAULT 0,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE TABLE IF NOT EXISTS order_state_transitions(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,from_status TEXT NOT NULL,to_status TEXT NOT NULL,transition_type TEXT NOT NULL,actor_type TEXT NOT NULL,actor_id UUID,reason TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,idempotency_key UUID,request_hash TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE UNIQUE INDEX IF NOT EXISTS idx_order_state_transitions_idempotency ON order_state_transitions(idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE TABLE IF NOT EXISTS outbox_events(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),aggregate_type TEXT NOT NULL,aggregate_id UUID NOT NULL,event_type TEXT NOT NULL,payload JSONB NOT NULL,event_key TEXT NOT NULL UNIQUE,published_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_orders_business_created_at ON orders (business_id, created_at DESC) WHERE business_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_business_source_created_at ON orders (business_id, source_type, created_at DESC) WHERE business_id IS NOT NULL;
