-- Curated marketplace content for search, discovery, and detail pages.
-- Uses realistic Indonesia-focused business data and deterministic Picsum images.

INSERT INTO content_items (
  owner_id,
  content_type,
  slug,
  title,
  summary,
  body,
  pricing_mode,
  price_cents,
  currency,
  tags,
  cover_image,
  category,
  content_status,
  rating,
  review_count,
  metadata,
  created_at,
  updated_at
) VALUES
(
  '00000000-0000-0000-0000-000000000511',
  'product',
  'supplier-cemilan-kemasan-reseller-bekasi',
  'Supplier cemilan kemasan untuk reseller dan toko Bekasi',
  'Snack kiloan, keripik, makaroni, dan bumbu tabur dengan MOQ ramah warung dan toko kecil.',
  'Cocok untuk warung, booth sekolah, dan reseller yang butuh stok cepat putar dengan pengiriman rutin Jabodetabek. Tersedia opsi repack sederhana dan jadwal restock mingguan.',
  'fixed',
  18500000,
  'IDR',
  ARRAY['supplier sembako', 'snack grosir', 'reseller', 'bekasi'],
  'https://picsum.photos/seed/lajukan-supply-cemilan-bekasi/1280/960',
  'product',
  'active',
  4.8,
  46,
  '{
    "market_side": "supply",
    "location": "Bekasi",
    "city": "Bekasi",
    "sector": "food_supply",
    "seller_type": "distributor",
    "moq": "mulai 10 pack per SKU",
    "shipping_area": ["Bekasi", "Jakarta", "Depok"],
    "lead_time": "same day untuk area inti"
  }'::jsonb,
  NOW() - INTERVAL '12 hours',
  NOW() - INTERVAL '2 hours'
),
(
  '00000000-0000-0000-0000-000000000511',
  'product',
  'supplier-bumbu-dan-bahan-baku-frozen-food-jakarta',
  'Supplier bumbu dan bahan baku frozen food untuk outlet Jakarta',
  'Ayam marinated, saus, tepung, sambal, dan topping minuman untuk usaha F&B skala outlet.',
  'Dirancang untuk cloud kitchen, booth frozen food, dan kedai cepat saji yang butuh stok harian lebih stabil. Bisa kirim rutin dan buat pola restock per area.',
  'fixed',
  24500000,
  'IDR',
  ARRAY['bahan baku', 'frozen food', 'supplier fnb', 'jakarta'],
  'https://picsum.photos/seed/lajukan-supply-frozen-jakarta/1280/960',
  'product',
  'active',
  4.9,
  53,
  '{
    "market_side": "supply",
    "location": "Jakarta",
    "city": "Jakarta",
    "sector": "food_supply",
    "seller_type": "supplier",
    "moq": "mulai 1 karton per item",
    "shipping_area": ["Jakarta", "Bekasi", "Tangerang"],
    "lead_time": "1 hari kerja"
  }'::jsonb,
  NOW() - INTERVAL '18 hours',
  NOW() - INTERVAL '5 hours'
),
(
  '00000000-0000-0000-0000-000000000512',
  'service',
  'jasa-kemasan-pouch-label-dan-mockup-bandung',
  'Jasa kemasan pouch, label, dan mockup katalog Bandung',
  'Pouch kraft, stiker brand, mockup produk, dan siap bantu susun layout listing marketplace.',
  'Paket ini cocok untuk brand kecil yang baru mau rapiin tampilan toko, butuh packaging launch, atau mau cek visual produk sebelum produksi lebih besar.',
  'fixed',
  9500000,
  'IDR',
  ARRAY['jasa kemasan', 'stiker label', 'mockup', 'bandung'],
  'https://picsum.photos/seed/lajukan-service-packaging-bandung/1280/960',
  'service',
  'active',
  4.7,
  38,
  '{
    "market_side": "supply",
    "location": "Bandung",
    "city": "Bandung",
    "sector": "brand_support",
    "service_scope": ["packaging design", "label print prep", "mockup katalog"],
    "delivery_time": "3-5 hari kerja",
    "work_mode": "remote + pickup"
  }'::jsonb,
  NOW() - INTERVAL '1 day',
  NOW() - INTERVAL '6 hours'
),
(
  '00000000-0000-0000-0000-000000000512',
  'service',
  'jasa-admin-marketplace-dan-optimasi-katalog-remote',
  'Jasa admin marketplace dan optimasi katalog remote',
  'Upload katalog, rapikan variasi, cek stok, dan bantu follow up chat pembeli harian.',
  'Layanan ini cocok untuk owner yang sudah punya produk tapi belum sempat jaga dashboard harian. Bisa bantu Shopee, Tokopedia, dan TikTok Shop untuk ritme operasional dasar.',
  'fixed',
  6500000,
  'IDR',
  ARRAY['admin marketplace', 'optimasi katalog', 'remote', 'operasional'],
  'https://picsum.photos/seed/lajukan-service-admin-marketplace/1280/960',
  'service',
  'active',
  4.8,
  29,
  '{
    "market_side": "supply",
    "location": "Bandung",
    "city": "Bandung",
    "sector": "operations_support",
    "service_scope": ["upload katalog", "variasi produk", "chat buyer", "stok harian"],
    "delivery_time": "mulai 1 hari onboarding",
    "work_mode": "remote"
  }'::jsonb,
  NOW() - INTERVAL '1 day 6 hours',
  NOW() - INTERVAL '7 hours'
),
(
  '00000000-0000-0000-0000-000000000514',
  'property',
  'booth-pop-up-sarinah-akhir-pekan-jakarta',
  'Booth pop-up akhir pekan area Sarinah Jakarta',
  'Spot pop-up untuk F&B, craft, beauty, dan tenant komunitas dengan traffic pengunjung akhir pekan.',
  'Cocok untuk brand yang ingin tes produk, buka booth campaign, atau ikut tenant jangka pendek di area pusat kota. Sudah ada alur registrasi tenant dan jam operasional jelas.',
  'fixed',
  42000000,
  'IDR',
  ARRAY['booth bazaar', 'pop-up store', 'jakarta pusat', 'tenant event'],
  'https://picsum.photos/seed/lajukan-property-sarinah/1280/960',
  'property',
  'active',
  4.6,
  17,
  '{
    "market_side": "supply",
    "location": "Jakarta Pusat",
    "city": "Jakarta",
    "sector": "event_space",
    "property_type": "booth",
    "rental_period": "3 hari",
    "traffic_note": "ramai Jumat-Minggu",
    "available_slots": 4
  }'::jsonb,
  NOW() - INTERVAL '1 day 12 hours',
  NOW() - INTERVAL '8 hours'
),
(
  '00000000-0000-0000-0000-000000000514',
  'property',
  'kios-food-court-dekat-kampus-ugm-yogyakarta',
  'Kios food court dekat kampus UGM Yogyakarta',
  'Kios siap pakai untuk minuman, rice bowl, atau snack dengan aliran mahasiswa dan pekerja sekitar.',
  'Sudah ada area duduk bersama, jam operasional malam, dan format sewa bulanan. Cocok untuk brand yang ingin buka titik jual tetap tanpa renovasi besar.',
  'fixed',
  85000000,
  'IDR',
  ARRAY['kios food court', 'yogyakarta', 'lokasi jualan', 'kampus'],
  'https://picsum.photos/seed/lajukan-property-ugm/1280/960',
  'property',
  'active',
  4.7,
  22,
  '{
    "market_side": "supply",
    "location": "Yogyakarta",
    "city": "Yogyakarta",
    "sector": "food_space",
    "property_type": "kios",
    "rental_period": "bulanan",
    "traffic_note": "ramai sore sampai malam",
    "available_slots": 2
  }'::jsonb,
  NOW() - INTERVAL '2 days',
  NOW() - INTERVAL '10 hours'
),
(
  '00000000-0000-0000-0000-000000000513',
  'tool_rental',
  'sewa-freezer-display-untuk-gelato-dan-frozen-food-denpasar',
  'Sewa freezer display untuk gelato dan frozen food Denpasar',
  'Freezer display, chiller showcase, dan support setup untuk booth event sampai outlet tetap.',
  'Paket sewa cocok untuk tenant musiman, launching menu beku, atau tenant mall yang butuh alat dingin tanpa beli unit baru. Tersedia opsi antar pasang.',
  'fixed',
  7800000,
  'IDR',
  ARRAY['sewa freezer', 'chiller showcase', 'denpasar', 'alat dingin'],
  'https://picsum.photos/seed/lajukan-rental-freezer-denpasar/1280/960',
  'tool_rental',
  'active',
  4.8,
  19,
  '{
    "market_side": "supply",
    "location": "Denpasar",
    "city": "Denpasar",
    "sector": "tool_rental",
    "asset_type": "freezer_display",
    "availability_status": "ready",
    "rental_period": "harian / mingguan",
    "support": ["antar pasang", "pickup", "basic maintenance"]
  }'::jsonb,
  NOW() - INTERVAL '2 days 6 hours',
  NOW() - INTERVAL '4 hours'
),
(
  '00000000-0000-0000-0000-000000000515',
  'freelancer',
  'live-host-dan-content-creator-untuk-brand-beauty-dan-fnb',
  'Live host dan content creator untuk brand beauty, fashion, dan F&B lokal.',
  'Biasa handle live commerce, short video, script selling, dan demo produk untuk campaign mingguan.',
  'Cocok untuk owner yang sudah punya stok tapi butuh eksekusi live dan konten yang lebih konsisten. Bisa bantu briefing, rundown, dan evaluasi live harian.',
  'fixed',
  17500000,
  'IDR',
  ARRAY['live host', 'content creator', 'tiktok shop', 'surabaya'],
  'https://picsum.photos/seed/lajukan-freelancer-livehost/1280/960',
  'freelancer',
  'active',
  4.9,
  41,
  '{
    "market_side": "supply",
    "location": "Surabaya",
    "city": "Surabaya",
    "sector": "creator_services",
    "professional_title": "Live host & content creator",
    "skills": ["live host", "short video", "script selling", "demo produk"],
    "hourly_rate": 175000
  }'::jsonb,
  NOW() - INTERVAL '2 days 12 hours',
  NOW() - INTERVAL '3 hours'
),
(
  '00000000-0000-0000-0000-000000000515',
  'freelancer',
  'admin-marketplace-harian-untuk-shopee-dan-tokopedia',
  'Admin marketplace harian untuk Shopee, Tokopedia, dan follow up chat pembeli.',
  'Bisa bantu upload produk, perapihan variasi, optimasi judul, dan rekap pesanan dasar.',
  'Cocok untuk owner yang belum sempat pegang dashboard harian tapi butuh ritme operasional tetap jalan. Bisa remote dan onboarding cepat.',
  'fixed',
  12000000,
  'IDR',
  ARRAY['admin marketplace', 'shopee', 'tokopedia', 'remote'],
  'https://picsum.photos/seed/lajukan-freelancer-admin/1280/960',
  'freelancer',
  'active',
  4.8,
  35,
  '{
    "market_side": "supply",
    "location": "Surabaya",
    "city": "Surabaya",
    "sector": "operations_support",
    "professional_title": "Marketplace admin",
    "skills": ["upload katalog", "chat buyer", "stok harian", "promo dashboard"],
    "hourly_rate": 120000
  }'::jsonb,
  NOW() - INTERVAL '3 days',
  NOW() - INTERVAL '12 hours'
),
(
  '00000000-0000-0000-0000-000000000518',
  'product',
  'butuh-supplier-bumbu-dan-sambal-untuk-8-outlet-jakarta',
  'Butuh supplier bumbu dan sambal siap pakai untuk 8 outlet Jakarta.',
  'Cari partner pasokan yang konsisten untuk bumbu dasar, sambal kemasan, dan item cepat restock.',
  'Owner sedang konsolidasi pembelian antar outlet supaya stok lebih stabil dan rasa tetap sama. Prioritas untuk supplier yang bisa kirim rutin ke Jakarta Timur dan Bekasi.',
  'request',
  16000000,
  'IDR',
  ARRAY['butuh supplier', 'bumbu dapur', 'jakarta', 'outlet fnb'],
  'https://picsum.photos/seed/lajukan-demand-bumbu-jakarta/1280/960',
  'product',
  'active',
  0,
  0,
  '{
    "market_side": "demand",
    "location": "Jakarta Timur",
    "city": "Jakarta",
    "sector": "food_operations",
    "brand": "Bumbu dasar, sambal kemasan, item restock cepat",
    "stock": 8,
    "delivery_estimate": "mulai minggu ini",
    "min_order_qty": 1,
    "specs": "Cari partner pasokan konsisten untuk bumbu dasar, sambal kemasan, dan item cepat restock. Prioritas kirim rutin ke Jakarta Timur dan Bekasi.",
    "address": "Jakarta Timur dan Bekasi",
    "listing_mode": "detail",
    "listing_form_version": 4
  }'::jsonb,
  NOW() - INTERVAL '8 hours',
  NOW() - INTERVAL '1 hour'
),
(
  '00000000-0000-0000-0000-000000000517',
  'service',
  'cari-reseller-skincare-dan-channel-live-commerce-untuk-koleksi-launch-baru',
  'Cari reseller skincare dan channel live commerce untuk koleksi launch baru.',
  'Butuh reseller aktif, booth kampus, dan host live yang siap bantu aktivasi launch batch awal.',
  'Brand sedang test distribusi baru untuk paket launch dan butuh partner yang bisa gerak cepat. Lebih cocok untuk channel reseller, host live, dan booth/event kecil yang sudah punya audience awal.',
  'request',
  12000000,
  'IDR',
  ARRAY['cari reseller', 'skincare', 'bandung', 'live commerce'],
  'https://picsum.photos/seed/lajukan-demand-skincare-bandung/1280/960',
  'service',
  'active',
  0,
  0,
  '{
    "market_side": "demand",
    "location": "Bandung",
    "city": "Bandung",
    "sector": "beauty_retail",
    "work_mode": "hybrid",
    "service_scope": "Aktivasi channel reseller, booth kampus, dan live commerce untuk koleksi launch baru.",
    "deliverables": "Shortlist partner channel, host live siap jualan, dan rencana aktivasi awal.",
    "area_served": "Bandung dan distribusi online nasional",
    "delivery_time": "launch akhir bulan",
    "client_requirements": "Open untuk reseller aktif, booth kampus, host live dengan audience kecil, dan partner yang bisa gerak cepat.",
    "listing_mode": "detail",
    "listing_form_version": 4
  }'::jsonb,
  NOW() - INTERVAL '16 hours',
  NOW() - INTERVAL '90 minutes'
),
(
  '00000000-0000-0000-0000-000000000518',
  'service',
  'butuh-jasa-kemasan-frozen-food-plus-desain-label-bekasi',
  'Butuh jasa kemasan frozen food plus desain label untuk batch baru.',
  'Cari vendor yang bisa bantu pouch, stiker, dan revisi visual dasar dalam satu jalur kerja.',
  'Fokus utama saat ini adalah kemasan yang cepat siap jual untuk stok mingguan. Lebih cocok untuk vendor yang bisa kasih mockup cepat dan revisi ringan tanpa proses panjang.',
  'request',
  8500000,
  'IDR',
  ARRAY['butuh jasa kemasan', 'frozen food', 'bekasi', 'desain label'],
  'https://picsum.photos/seed/lajukan-demand-packaging-bekasi/1280/960',
  'service',
  'active',
  0,
  0,
  '{
    "market_side": "demand",
    "location": "Bekasi",
    "city": "Bekasi",
    "sector": "brand_support",
    "work_mode": "hybrid",
    "service_scope": "Kemasan pouch, label, dan revisi visual dasar untuk batch baru.",
    "deliverables": "Pouch siap cetak, label, mockup, dan revisi ringan.",
    "area_served": "Bekasi / remote",
    "delivery_time": "maksimal 5 hari",
    "client_requirements": "Batch awal sudah siap produksi dan butuh vendor yang bisa mockup cepat tanpa proses panjang.",
    "listing_mode": "detail",
    "listing_form_version": 4
  }'::jsonb,
  NOW() - INTERVAL '20 hours',
  NOW() - INTERVAL '80 minutes'
),
(
  '00000000-0000-0000-0000-000000000517',
  'property',
  'cari-booth-bazaar-ramadan-area-bandung-timur',
  'Cari booth bazaar Ramadan area Bandung Timur untuk modest fashion dan gift set.',
  'Butuh space 3 sampai 5 hari dengan traffic keluarga, akses loading mudah, dan jam malam aman.',
  'Brand sedang siapkan koleksi musiman dan lebih cocok ke space yang ramai sore sampai malam. Prioritas untuk venue dengan tenant campuran F&B, gift, dan fashion.',
  'request',
  14000000,
  'IDR',
  ARRAY['cari booth', 'bazaar ramadan', 'bandung', 'fashion booth'],
  'https://picsum.photos/seed/lajukan-demand-booth-bandung/1280/960',
  'property',
  'active',
  0,
  0,
  '{
    "market_side": "demand",
    "location": "Bandung Timur",
    "city": "Bandung",
    "sector": "event_space",
    "listing_purpose": "rent",
    "property_type": "commercial",
    "area_sqm": 12,
    "available_from": "2026-04-20",
    "address": "Bandung Timur, dekat tenant keluarga dengan akses loading mudah",
    "amenities": "Traffic keluarga dan komunitas, tenant campuran F&B, gift, dan fashion",
    "listing_mode": "detail",
    "listing_form_version": 4
  }'::jsonb,
  NOW() - INTERVAL '1 day 3 hours',
  NOW() - INTERVAL '70 minutes'
),
(
  '00000000-0000-0000-0000-000000000516',
  'tool_rental',
  'butuh-chiller-showcase-untuk-event-3-hari-di-medan',
  'Butuh chiller showcase untuk event minuman selama 3 hari di Medan.',
  'Cari vendor sewa yang bisa antar pasang, standby singkat saat event, dan pickup setelah acara selesai.',
  'Request ini cocok untuk partner rental alat pendingin yang terbiasa handle event atau booth festival. Target alat harus siap H-1 dan tetap stabil selama jam ramai.',
  'request',
  6500000,
  'IDR',
  ARRAY['butuh chiller', 'event medan', 'sewa alat dingin', 'showcase'],
  'https://picsum.photos/seed/lajukan-demand-chiller-medan/1280/960',
  'tool_rental',
  'active',
  0,
  0,
  '{
    "market_side": "demand",
    "location": "Medan",
    "city": "Medan",
    "sector": "tool_rental",
    "brand": "Chiller showcase event",
    "model_name": "Display minuman kapasitas besar",
    "specs": "Target alat siap H-1 dan stabil selama jam ramai untuk event 3 hari.",
    "condition": "good",
    "rental_rate_type": "daily",
    "minimum_rental_days": 3,
    "pickup_location": "Medan",
    "delivery_estimate": "event minggu depan",
    "usage_restrictions": "Butuh antar pasang H-1 dan pickup setelah acara.",
    "listing_mode": "detail",
    "listing_form_version": 4
  }'::jsonb,
  NOW() - INTERVAL '1 day 9 hours',
  NOW() - INTERVAL '65 minutes'
),
(
  '00000000-0000-0000-0000-000000000517',
  'freelancer',
  'cari-live-host-beauty-untuk-launch-akhir-bulan-jakarta',
  'Cari live host beauty untuk launch akhir bulan dan jadwal 4 sesi live.',
  'Butuh host yang enak jualan, nyaman on camera, dan bisa bantu briefing produk sebelum siaran.',
  'Campaign ini fokus ke bundle launch dan repeat audience dari live sebelumnya. Lebih cocok untuk host yang biasa handle skincare, hampers, atau fashion basic.',
  'request',
  7000000,
  'IDR',
  ARRAY['cari live host', 'beauty', 'jakarta', 'launch campaign'],
  'https://picsum.photos/seed/lajukan-demand-livehost-jakarta/1280/960',
  'freelancer',
  'active',
  0,
  0,
  '{
    "market_side": "demand",
    "location": "Jakarta",
    "city": "Jakarta",
    "sector": "creator_services",
    "professional_title": "Live host campaign",
    "deadline": "akhir bulan",
    "session_count": 4,
    "preferred_skills": ["live selling", "beauty demo", "script reading"]
  }'::jsonb,
  NOW() - INTERVAL '22 hours',
  NOW() - INTERVAL '50 minutes'
),
(
  '00000000-0000-0000-0000-000000000516',
  'job',
  'butuh-admin-marketplace-shift-sore-untuk-brand-minuman-yogyakarta',
  'Butuh admin marketplace shift sore untuk brand minuman dengan ritme chat cepat.',
  'Tugas fokus ke chat buyer, input pesanan, follow up komplain ringan, dan update stok dashboard.',
  'Posisi ini cocok untuk operator yang terbiasa kerja detail dan bisa jaga ritme dashboard harian. Prioritas kandidat yang pernah pegang Shopee atau Tokopedia.',
  'request',
  4200000,
  'IDR',
  ARRAY['lowongan admin marketplace', 'yogyakarta', 'shift sore', 'operasional'],
  'https://picsum.photos/seed/lajukan-job-admin-yogyakarta/1280/960',
  'job',
  'active',
  0,
  0,
  '{
    "market_side": "demand",
    "location": "Yogyakarta",
    "city": "Yogyakarta",
    "sector": "operations_support",
    "employment_type": "part-time",
    "work_mode": "hybrid",
    "level": "junior",
    "salary_range": "4.2-5.2 juta"
  }'::jsonb,
  NOW() - INTERVAL '1 day 15 hours',
  NOW() - INTERVAL '45 minutes'
),
(
  '00000000-0000-0000-0000-000000000514',
  'job',
  'crew-booth-dan-pic-lapangan-untuk-weekend-market-bandung',
  'Crew booth dan PIC lapangan untuk weekend market Bandung.',
  'Tugas mencakup set up tenant, koordinasi vendor ringan, check in tenant, dan jaga ritme acara.',
  'Posisi ini cocok untuk kandidat yang nyaman kerja lapangan dan rapi koordinasi. Jam kerja padat di akhir pekan dengan kemungkinan lanjut ke event berikutnya.',
  'request',
  5000000,
  'IDR',
  ARRAY['crew event', 'pic lapangan', 'bandung', 'weekend market'],
  'https://picsum.photos/seed/lajukan-job-event-bandung/1280/960',
  'job',
  'active',
  0,
  0,
  '{
    "market_side": "demand",
    "location": "Bandung",
    "city": "Bandung",
    "sector": "event_operations",
    "employment_type": "contract",
    "work_mode": "onsite",
    "level": "junior",
    "salary_range": "5-6 juta"
  }'::jsonb,
  NOW() - INTERVAL '2 days 3 hours',
  NOW() - INTERVAL '40 minutes'
)
ON CONFLICT (slug) DO UPDATE
SET
  owner_id = EXCLUDED.owner_id,
  content_type = EXCLUDED.content_type,
  title = EXCLUDED.title,
  summary = EXCLUDED.summary,
  body = EXCLUDED.body,
  pricing_mode = EXCLUDED.pricing_mode,
  price_cents = EXCLUDED.price_cents,
  currency = EXCLUDED.currency,
  tags = EXCLUDED.tags,
  cover_image = EXCLUDED.cover_image,
  category = EXCLUDED.category,
  content_status = EXCLUDED.content_status,
  rating = EXCLUDED.rating,
  review_count = EXCLUDED.review_count,
  metadata = EXCLUDED.metadata,
  updated_at = EXCLUDED.updated_at;

SELECT 1;
