CREATE EXTENSION IF NOT EXISTS postgres_fdw;
CREATE SCHEMA IF NOT EXISTS legacy;
DROP SERVER IF EXISTS legacy_marketplace CASCADE;
CREATE SERVER legacy_marketplace FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host :'legacy_host', port :'legacy_port', dbname 'marketplace_db');
CREATE USER MAPPING FOR CURRENT_USER SERVER legacy_marketplace OPTIONS (user :'legacy_user', password :'legacy_password');
IMPORT FOREIGN SCHEMA public LIMIT TO (businesses) FROM SERVER legacy_marketplace INTO legacy;
CREATE TABLE IF NOT EXISTS businesses (LIKE legacy.businesses INCLUDING DEFAULTS);
INSERT INTO businesses SELECT * FROM legacy.businesses ON CONFLICT DO NOTHING;\nCREATE EXTENSION IF NOT EXISTS postgres_fdw;
CREATE SCHEMA IF NOT EXISTS legacy;
DROP SERVER IF EXISTS legacy_marketplace CASCADE;
CREATE SERVER legacy_marketplace FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host :'legacy_host', port :'legacy_port', dbname 'marketplace_db');
CREATE USER MAPPING FOR CURRENT_USER SERVER legacy_marketplace OPTIONS (user :'legacy_user', password :'legacy_password');
IMPORT FOREIGN SCHEMA public LIMIT TO (business_locations) FROM SERVER legacy_marketplace INTO legacy;
CREATE TABLE IF NOT EXISTS business_locations (LIKE legacy.business_locations INCLUDING DEFAULTS);
INSERT INTO business_locations SELECT * FROM legacy.business_locations ON CONFLICT DO NOTHING;\nCREATE EXTENSION IF NOT EXISTS postgres_fdw;
CREATE SCHEMA IF NOT EXISTS legacy;
DROP SERVER IF EXISTS legacy_marketplace CASCADE;
CREATE SERVER legacy_marketplace FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host :'legacy_host', port :'legacy_port', dbname 'marketplace_db');
CREATE USER MAPPING FOR CURRENT_USER SERVER legacy_marketplace OPTIONS (user :'legacy_user', password :'legacy_password');
IMPORT FOREIGN SCHEMA public LIMIT TO (business_profiles) FROM SERVER legacy_marketplace INTO legacy;
CREATE TABLE IF NOT EXISTS business_profiles (LIKE legacy.business_profiles INCLUDING DEFAULTS);
INSERT INTO business_profiles SELECT * FROM legacy.business_profiles ON CONFLICT DO NOTHING;